<?php
/**
 * install.php — Visual Design Journey one-shot web installer
 * DELETE this file after installation is complete.
 */
define('INSTALL_LOCK', __DIR__ . '/config/.installed');

// Block re-installation if already done
if (file_exists(INSTALL_LOCK)) {
    http_response_code(403);
    die('<h2 style="font-family:sans-serif;color:#7F77DD;text-align:center;padding:80px">
        Already installed. <a href="/index.php">Go to site →</a><br>
        <small style="color:#999">Delete install.php for security.</small>
    </h2>');
}

$step   = (int)($_POST['step'] ?? $_GET['step'] ?? 1);
$errors = [];
$info   = [];

/* ── STEP 2: Check requirements ─────────────────────────────────────────── */
function checkRequirements(): array {
    $checks = [
        ['PHP ≥ 8.0',        version_compare(PHP_VERSION, '8.0.0', '>=')],
        ['PDO extension',    extension_loaded('pdo')],
        ['PDO MySQL driver', extension_loaded('pdo_mysql')],
        ['GD extension',     extension_loaded('gd')],
        ['FileInfo ext.',    extension_loaded('fileinfo')],
        ['Session support',  function_exists('session_start')],
        ['config/ writable', is_writable(__DIR__ . '/config')],
        ['Root writable',    is_writable(__DIR__)],
    ];
    $pass = true;
    foreach ($checks as &$c) {
        if (!$c[1]) $pass = false;
    }
    return [$checks, $pass];
}

/* ── STEP 3: Run installation ────────────────────────────────────────────── */
function runInstall(array $d): array {
    $errors = [];

    // 1. Test DB connection
    try {
        $dsn = 'mysql:host=' . $d['db_host'] . ';charset=utf8mb4';
        $pdo = new PDO($dsn, $d['db_user'], $d['db_pass'], [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
    } catch (PDOException $e) {
        return ['Cannot connect to MySQL: ' . $e->getMessage()];
    }

    // 2. Create database if not exists
    try {
        $pdo->exec('CREATE DATABASE IF NOT EXISTS `' . $d['db_name'] . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
        $pdo->exec('USE `' . $d['db_name'] . '`');
    } catch (PDOException $e) {
        return ['Cannot create database: ' . $e->getMessage()];
    }

    // 3. Run schema.sql
    $schema = file_get_contents(__DIR__ . '/schema.sql');
    foreach (array_filter(array_map('trim', explode(';', $schema))) as $sql) {
        if ($sql === '') continue;
        try { $pdo->exec($sql); } catch (PDOException $e) {
            $errors[] = 'Schema error: ' . $e->getMessage() . ' — SQL: ' . substr($sql, 0, 80);
        }
    }
    if ($errors) return $errors;

    // 4. Run seed.sql if requested
    if (!empty($d['run_seed'])) {
        $seed = file_get_contents(__DIR__ . '/seed.sql');
        foreach (array_filter(array_map('trim', explode(';', $seed))) as $sql) {
            if ($sql === '') continue;
            try { $pdo->exec($sql); } catch (PDOException $e) {
                // Seed errors are soft (duplicate key OK)
            }
        }
    }

    // 5. Write config/db.local.php (production credentials — never overwritten by deploys)
    $siteUrl    = rtrim($d['site_url'], '/');
    $installDate = date('Y-m-d H:i:s');
    $configContent = <<<PHP
<?php
/**
 * config/db.local.php — Production credentials
 * Generated by installer on {$installDate}
 * DO NOT upload this file — it lives only on the server.
 */
define('DB_HOST',    '{$d['db_host']}');
define('DB_NAME',    '{$d['db_name']}');
define('DB_USER',    '{$d['db_user']}');
define('DB_PASS',    '{$d['db_pass']}');
define('DB_CHARSET', 'utf8mb4');
define('SITE_URL',   '$siteUrl');
define('SITE_NAME',  'Visual Design Journey');
PHP;
    file_put_contents(__DIR__ . '/config/db.local.php', $configContent);

    // 6. Create uploads directory structure
    $dirs = [
        __DIR__ . '/uploads',
        __DIR__ . '/uploads/boards',
        __DIR__ . '/uploads/avatars',
    ];
    foreach ($dirs as $dir) {
        if (!is_dir($dir)) mkdir($dir, 0755, true);
        // Drop an .htaccess to block PHP execution in uploads
        $htaccessPath = $dir . '/.htaccess';
        if (!file_exists($htaccessPath)) {
            file_put_contents($htaccessPath, "php_flag engine off\nOptions -Indexes\n");
        }
    }

    // 7. Write lock file
    file_put_contents(INSTALL_LOCK, date('Y-m-d H:i:s'));

    return [];
}

/* ── HANDLE STEP 3 POST ──────────────────────────────────────────────────── */
$installDone = false;
if ($step === 3 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $d = [
        'db_host'  => trim($_POST['db_host']  ?? 'localhost'),
        'db_name'  => trim($_POST['db_name']  ?? ''),
        'db_user'  => trim($_POST['db_user']  ?? ''),
        'db_pass'  => $_POST['db_pass']  ?? '',
        'site_url' => trim($_POST['site_url'] ?? ''),
        'run_seed' => !empty($_POST['run_seed']),
    ];

    if (!$d['db_name']) $errors[] = 'Database name is required.';
    if (!$d['db_user']) $errors[] = 'Database user is required.';
    if (!$d['site_url']) $errors[] = 'Site URL is required.';

    if (!$errors) {
        $errors = runInstall($d);
        if (!$errors) $installDone = true;
    }
}

[$reqChecks, $reqPass] = checkRequirements();

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Install — Visual Design Journey</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', system-ui, sans-serif; background: #F8F9FA; color: #0F172A; line-height: 1.6; }
  .wrap { max-width: 640px; margin: 60px auto; padding: 0 20px 80px; }
  .brand { font-family: 'Georgia', serif; font-size: 22px; font-weight: 700; color: #7F77DD; margin-bottom: 40px; text-align: center; }
  .card { background: #fff; border: 0.5px solid #E9ECEF; border-radius: 12px; padding: 40px; margin-bottom: 24px; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 6px; }
  h2 { font-size: 15px; font-weight: 600; margin-bottom: 16px; color: #454F5E; text-transform: uppercase; letter-spacing: 0.08em; }
  p { color: #454F5E; font-size: 14px; margin-bottom: 0; }
  .steps { display: flex; gap: 0; margin-bottom: 32px; }
  .step { flex: 1; text-align: center; padding: 10px; font-size: 12px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; border-bottom: 2px solid #E9ECEF; color: #999; }
  .step.active { color: #7F77DD; border-color: #7F77DD; }
  .step.done { color: #22c55e; border-color: #22c55e; }
  .check-row { display: flex; align-items: center; justify-content: space-between; padding: 10px 0; border-bottom: 0.5px solid #E9ECEF; font-size: 14px; }
  .check-row:last-child { border-bottom: none; }
  .badge { font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 999px; }
  .badge.ok { background: #dcfce7; color: #166534; }
  .badge.fail { background: #FFDAD6; color: #93000a; }
  .form-group { margin-bottom: 18px; }
  label { display: block; font-size: 12px; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; color: #454F5E; margin-bottom: 6px; }
  input[type=text], input[type=password], input[type=url] {
    width: 100%; padding: 10px 14px; border: 0.5px solid #E9ECEF; border-radius: 8px;
    background: #fff; color: #0F172A; font-size: 15px; outline: none;
    transition: border-color 0.15s;
  }
  input:focus { border-color: #7F77DD; }
  .hint { font-size: 12px; color: #999; margin-top: 4px; }
  .btn { display: inline-flex; align-items: center; gap: 6px; padding: 12px 28px; font-size: 14px; font-weight: 600; border-radius: 999px; border: none; cursor: pointer; transition: opacity 0.15s; }
  .btn-primary { background: #7F77DD; color: #fff; }
  .btn-primary:hover { opacity: 0.85; }
  .btn-secondary { background: transparent; color: #0F172A; border: 0.5px solid #E9ECEF; }
  .alert { padding: 12px 16px; border-radius: 8px; font-size: 13px; margin-bottom: 16px; }
  .alert-error { background: #FFDAD6; color: #93000a; border: 0.5px solid #f5c6c6; }
  .alert-success { background: #dcfce7; color: #166534; border: 0.5px solid #bbf7d0; }
  .check-label { display: flex; align-items: center; gap: 10px; font-size: 14px; cursor: pointer; }
  .check-label input { width: auto; cursor: pointer; }
  .success-icon { font-size: 48px; text-align: center; margin-bottom: 16px; }
  .next-steps { list-style: none; }
  .next-steps li { padding: 8px 0; border-bottom: 0.5px solid #E9ECEF; font-size: 14px; display: flex; align-items: start; gap: 8px; }
  .next-steps li:last-child { border: none; }
  .step-num { background: #7F77DD; color: #fff; border-radius: 50%; width: 20px; height: 20px; display: inline-flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700; flex-shrink: 0; margin-top: 2px; }
  code { background: #F8F9FA; border: 0.5px solid #E9ECEF; border-radius: 4px; padding: 2px 6px; font-family: monospace; font-size: 13px; color: #7F77DD; }
  .warn { background: #fff7ed; border: 0.5px solid #fed7aa; color: #92400e; padding: 12px 16px; border-radius: 8px; font-size: 13px; margin-top: 16px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="brand">Visual Design Journey — Installer</div>

  <?php if ($installDone): ?>
  <!-- ── SUCCESS ── -->
  <div class="card">
    <div class="success-icon">🎉</div>
    <h1 style="text-align:center;margin-bottom:8px;">Installation Complete!</h1>
    <p style="text-align:center;margin-bottom:32px;">Your site is ready. Complete the steps below to go live.</p>
    <h2>Next Steps</h2>
    <ul class="next-steps">
      <li>
        <span class="step-num">1</span>
        <span><strong>Delete install.php</strong> from your server immediately — it's a security risk if left behind.</span>
      </li>
      <li>
        <span class="step-num">2</span>
        <span>Upload the <code>.htaccess</code> file to the root of your subdomain if not already there.</span>
      </li>
      <li>
        <span class="step-num">3</span>
        <span>Make sure <code>uploads/</code> folder is writable by PHP (<code>chmod 755</code>).</span>
      </li>
      <li>
        <span class="step-num">4</span>
        <span>Log in with seed data: <code>studio@gmail.com</code> / <code>password123</code></span>
      </li>
    </ul>
    <div style="text-align:center;margin-top:32px;">
      <a href="/index.php" class="btn btn-primary">Go to Site →</a>
    </div>
    <div class="warn">⚠️ <strong>Security:</strong> Delete <code>install.php</code> before sharing the URL publicly.</div>
  </div>

  <?php elseif ($step === 1): ?>
  <!-- ── STEP 1: Welcome ── -->
  <div class="steps">
    <div class="step active">1. Welcome</div>
    <div class="step">2. Requirements</div>
    <div class="step">3. Database</div>
  </div>
  <div class="card">
    <h1>Welcome</h1>
    <p style="margin:12px 0 24px;">This wizard will set up Visual Design Journey on your server in under 2 minutes.</p>
    <h2>Before you start</h2>
    <p style="margin-bottom:8px;">You'll need:</p>
    <ul style="font-size:14px;color:#454F5E;margin:0 0 24px 18px;">
      <li>A MySQL database (or credentials to create one)</li>
      <li>PHP 8.0+ with PDO, GD, FileInfo extensions</li>
      <li>The full site files uploaded to your subdomain root</li>
    </ul>
    <form method="POST">
      <input type="hidden" name="step" value="2"/>
      <button type="submit" class="btn btn-primary">Check Requirements →</button>
    </form>
  </div>

  <?php elseif ($step === 2): ?>
  <!-- ── STEP 2: Requirements ── -->
  <div class="steps">
    <div class="step done">1. Welcome</div>
    <div class="step active">2. Requirements</div>
    <div class="step">3. Database</div>
  </div>
  <div class="card">
    <h1>Requirements Check</h1>
    <p style="margin-bottom:20px;">PHP <?= PHP_VERSION ?> running on <?= PHP_OS ?>.</p>
    <?php foreach ($reqChecks as [$label, $ok]): ?>
    <div class="check-row">
      <span><?= $label ?></span>
      <span class="badge <?= $ok ? 'ok' : 'fail' ?>"><?= $ok ? '✓ OK' : '✗ Missing' ?></span>
    </div>
    <?php endforeach; ?>
    <div style="margin-top:24px;">
      <?php if ($reqPass): ?>
        <div class="alert alert-success">All requirements met. Ready to install.</div>
        <form method="POST">
          <input type="hidden" name="step" value="3"/>
          <button type="submit" class="btn btn-primary">Continue to Database Setup →</button>
        </form>
      <?php else: ?>
        <div class="alert alert-error">Some requirements are missing. Please fix them before continuing.</div>
        <form method="POST">
          <input type="hidden" name="step" value="2"/>
          <button type="submit" class="btn btn-secondary">Re-check</button>
        </form>
      <?php endif; ?>
    </div>
  </div>

  <?php else: ?>
  <!-- ── STEP 3: Database ── -->
  <div class="steps">
    <div class="step done">1. Welcome</div>
    <div class="step done">2. Requirements</div>
    <div class="step active">3. Database</div>
  </div>
  <div class="card">
    <h1>Database & Site Setup</h1>
    <p style="margin-bottom:24px;">Enter your database credentials. The installer will create tables and optionally load demo data.</p>

    <?php foreach ($errors as $err): ?>
      <div class="alert alert-error"><?= htmlspecialchars($err) ?></div>
    <?php endforeach; ?>

    <form method="POST">
      <input type="hidden" name="step" value="3"/>

      <h2>Database</h2>
      <div class="form-group">
        <label for="db_host">Database Host</label>
        <input type="text" id="db_host" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" placeholder="localhost"/>
        <div class="hint">Usually <code>localhost</code> on shared hosting.</div>
      </div>
      <div class="form-group">
        <label for="db_name">Database Name</label>
        <input type="text" id="db_name" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>" placeholder="visualdesign_db" required/>
      </div>
      <div class="form-group">
        <label for="db_user">Database User</label>
        <input type="text" id="db_user" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" placeholder="db_username" required/>
      </div>
      <div class="form-group">
        <label for="db_pass">Database Password</label>
        <input type="password" id="db_pass" name="db_pass" value="<?= htmlspecialchars($_POST['db_pass'] ?? '') ?>" placeholder="••••••••"/>
      </div>

      <h2 style="margin-top:24px;">Site</h2>
      <div class="form-group">
        <label for="site_url">Site URL</label>
        <input type="url" id="site_url" name="site_url" value="<?= htmlspecialchars($_POST['site_url'] ?? 'https://') ?>" placeholder="https://boards.yourdomain.com" required/>
        <div class="hint">No trailing slash. This is your subdomain URL.</div>
      </div>

      <div class="form-group">
        <label class="check-label">
          <input type="checkbox" name="run_seed" value="1" <?= !empty($_POST['run_seed']) ? 'checked' : 'checked' ?>/>
          Load demo data (25 curators, 50+ boards, sample notifications)
        </label>
        <div class="hint">Recommended for a first install so the site looks alive immediately.</div>
      </div>

      <div style="margin-top:24px;">
        <button type="submit" class="btn btn-primary">Install Now →</button>
      </div>
    </form>
  </div>
  <?php endif; ?>

</div>
</body>
</html>
