<?php
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_metrics.php';

$adsConfig = __DIR__ . '/../config/adsense.local.php';
$adsTxt = __DIR__ . '/../ads.txt';
$flash = '';
$flashType = 'success';

function adsenseStatus(bool $ok): string {
    return $ok ? '<span style="color:#16a34a;font-weight:700;">Ready</span>' : '<span style="color:#dc2626;font-weight:700;">Needs work</span>';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verifyCsrf();
    $action = $_POST['action'] ?? 'save_settings';
    $client = trim($_POST['adsense_client'] ?? '');
    $adsLine = trim($_POST['ads_txt_line'] ?? '');
    $autoAds = !empty($_POST['auto_ads']);

    if ($action === 'check_public_files') {
        $files = [
            'ads.txt' => __DIR__ . '/../ads.txt',
            'Blog index' => __DIR__ . '/../blog.php',
            'Privacy' => __DIR__ . '/../privacy.php',
            'About' => __DIR__ . '/../about.php',
            'Editorial Policy' => __DIR__ . '/../editorial-policy.php',
            'Contact' => __DIR__ . '/../contact.php',
            'Sitemap generator' => __DIR__ . '/../sitemap.xml.php',
        ];
        $missing = [];
        foreach ($files as $label => $path) {
            if (!is_file($path)) $missing[] = $label;
        }
        if ($missing) {
            $flash = 'Missing local file(s): ' . implode(', ', $missing) . '.';
            $flashType = 'error';
        } else {
            $flash = 'Public file check passed locally. Final live status still depends on hosting rewrites and cache.';
        }
    } else {
        if ($client !== '' && !preg_match('/^ca-pub-\d+$/', $client)) {
            $flash = 'Publisher ID must look like ca-pub-0000000000000000.';
            $flashType = 'error';
        } elseif ($adsLine !== '' && !preg_match('/^google\.com,\s*pub-\d+,\s*DIRECT,\s*f08c47fec0942fa0$/i', $adsLine)) {
            $flash = 'ads.txt line format is not valid. Paste the exact AdSense line.';
            $flashType = 'error';
        } else {
            $php = "<?php\n";
            $php .= "// Generated by /admin/adsense.php\n";
            $php .= "define('ADSENSE_CLIENT', " . var_export($client, true) . ");\n";
            $php .= "define('ADSENSE_AUTO_ADS', " . ($autoAds ? 'true' : 'false') . ");\n";
            file_put_contents($adsConfig, $php, LOCK_EX);

            if ($adsLine !== '') {
                file_put_contents($adsTxt, $adsLine . "\n", LOCK_EX);
            }

            $flash = 'AdSense settings saved.';
        }
    }
}

$currentClient = defined('ADSENSE_CLIENT') ? ADSENSE_CLIENT : '';
$currentAutoAds = defined('ADSENSE_AUTO_ADS') ? (bool)ADSENSE_AUTO_ADS : false;
$currentAdsTxt = is_file($adsTxt) ? trim(file_get_contents($adsTxt)) : '';
$readiness = adminAdsenseReadiness();
$activeAdsTxtLine = $readiness['active_line'];
$checks = $readiness['checks'];
$samplePostUrl = '';
try {
    $sampleSlug = $db->query("SELECT slug FROM blog_posts WHERE slug <> '' ORDER BY published_at DESC LIMIT 1")->fetchColumn();
    if ($sampleSlug) $samplePostUrl = blogPostUrl((string)$sampleSlug);
} catch (Throwable $e) {}

$csrf = csrfToken();
$currentPage = 'adsense';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AdSense — Admin</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <link rel="stylesheet" href="/admin/admin.css">
  <style>
    .adsense-form { display: grid; gap: 18px; max-width: 760px; }
    .adsense-form .form-input {
      width: 100%;
      min-height: 42px;
      padding: 10px 12px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: #fff;
      color: var(--text);
      font-size: 14px;
    }
    .adsense-form .form-input:focus {
      outline: none;
      border-color: var(--accent);
      box-shadow: 0 0 0 3px rgba(127,119,221,.12);
    }
    .adsense-note {
      padding: 12px 14px;
      border: 1px solid #fde68a;
      border-radius: 8px;
      background: #fffbeb;
      color: #92400e;
      font-size: 13px;
      line-height: 1.55;
    }
    .status-card{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:16px;border:1px solid var(--border);border-radius:10px;background:#fff;margin-bottom:16px}
    .status-pill{display:inline-flex;align-items:center;gap:8px;border-radius:999px;padding:7px 11px;font-size:13px;font-weight:700}
    .status-pill.ready{background:#dcfce7;color:#166534}
    .status-pill.warn{background:#fef3c7;color:#92400e}
    .preview-row{display:flex;gap:10px;flex-wrap:wrap}
  </style>
</head>
<body>
<?php require_once __DIR__ . '/_sidebar.php'; ?>
<main class="admin-main">
  <div class="admin-topbar">
    <div class="admin-header">
      <h1>AdSense</h1>
      <p>Configure publisher ID, ads.txt, and review application readiness.</p>
    </div>
    <button class="hamburger" id="hamburger"><i class="fa-solid fa-bars"></i></button>
  </div>

  <?php if ($flash): ?>
    <div class="flash flash-<?= $flashType === 'error' ? 'error' : 'success' ?>"><?= e($flash) ?></div>
  <?php endif; ?>

  <?php $readyClass = $readiness['status'] === 'Ready for review' ? 'ready' : 'warn'; ?>
  <div class="status-card">
    <div>
      <h2 style="font-size:16px;margin:0 0 6px;">Current AdSense Status</h2>
      <p style="margin:0;color:var(--text-muted);font-size:13px;">Keep ads modest while Google review is running. Auto Ads can stay off until approval.</p>
    </div>
    <span class="status-pill <?= e($readyClass) ?>">
      <i class="fa-solid <?= $readyClass === 'ready' ? 'fa-circle-check' : 'fa-triangle-exclamation' ?>"></i>
      <?= e($readiness['status']) ?>
    </span>
  </div>

  <div class="deploy-grid">
    <div class="admin-card">
      <div class="admin-card__header"><h2><i class="fa-brands fa-google"></i> AdSense Settings</h2></div>
      <div class="admin-card__body">
        <div class="adsense-note" style="margin-bottom:16px;">
          Paste the real values from your AdSense account. Placeholder examples do not activate ads and should not be submitted for review.
        </div>
        <form method="post" action="/admin/adsense.php" class="adsense-form">
          <input type="hidden" name="csrf_token" value="<?= e($csrf) ?>">
          <input type="hidden" name="action" value="save_settings">
          <div class="form-group">
            <label class="form-label" for="adsense_client">Publisher ID</label>
            <input class="form-input" id="adsense_client" name="adsense_client" value="<?= e($currentClient) ?>" placeholder="ca-pub-0000000000000000">
            <div class="form-hint">Paste the AdSense client ID. Ads stay disabled until this is valid.</div>
          </div>
          <div class="form-group">
            <label class="form-label" for="ads_txt_line">ads.txt line</label>
            <input class="form-input" id="ads_txt_line" name="ads_txt_line" value="<?= e($activeAdsTxtLine) ?>" placeholder="google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0">
            <div class="form-hint">Paste the exact line from AdSense Sites → ads.txt.</div>
          </div>
          <label style="display:flex;align-items:center;gap:8px;margin-bottom:16px;font-size:14px;">
            <input type="checkbox" name="auto_ads" value="1" <?= $currentAutoAds ? 'checked' : '' ?>>
            Enable Auto Ads after approval
          </label>
          <button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save Settings</button>
        </form>
      </div>
    </div>

    <div class="admin-card">
      <div class="admin-card__header"><h2><i class="fa-solid fa-list-check"></i> Readiness Checklist</h2></div>
      <div class="admin-card__body">
        <table class="admin-table">
          <tbody>
            <?php foreach ($checks as $label => $ok): ?>
              <tr>
                <td><?= e($label) ?></td>
                <td style="width:130px;"><?= adsenseStatus((bool)$ok) ?></td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="admin-card">
    <div class="admin-card__header"><h2><i class="fa-solid fa-link"></i> Quick Test Links</h2></div>
    <div class="admin-card__body">
      <div class="preview-row" style="margin-bottom:12px;">
      <a class="btn btn-secondary" href="/ads.txt" target="_blank"><i class="fa-solid fa-file-lines"></i> ads.txt</a>
      <a class="btn btn-secondary" href="/blog.php" target="_blank"><i class="fa-solid fa-newspaper"></i> Blog</a>
      <?php if ($samplePostUrl): ?>
        <a class="btn btn-secondary" href="<?= e($samplePostUrl) ?>" target="_blank"><i class="fa-solid fa-arrow-up-right-from-square"></i> Sample Post</a>
      <?php endif; ?>
      <a class="btn btn-secondary" href="/privacy.php" target="_blank"><i class="fa-solid fa-shield-halved"></i> Privacy</a>
      <a class="btn btn-secondary" href="/about.php" target="_blank"><i class="fa-solid fa-circle-info"></i> About</a>
      <a class="btn btn-secondary" href="/editorial-policy.php" target="_blank"><i class="fa-solid fa-pen-ruler"></i> Editorial Policy</a>
      <a class="btn btn-secondary" href="/sitemap.xml" target="_blank"><i class="fa-solid fa-sitemap"></i> Sitemap</a>
      </div>
      <form method="post" action="/admin/adsense.php">
        <input type="hidden" name="csrf_token" value="<?= e($csrf) ?>">
        <input type="hidden" name="action" value="check_public_files">
        <button class="btn btn-secondary" type="submit"><i class="fa-solid fa-list-check"></i> Check Public Files</button>
      </form>
    </div>
  </div>
</main>
</body>
</html>
