<?php
/**
 * admin/adsterra.php — Adsterra Publisher Statistics Panel
 *
 * Fetches real-time stats from the Adsterra Publisher API v3.
 * API docs: https://kb.adsterra.com/article/127-publisher-api-overview
 *
 * Required: Adsterra Publisher API key (obtainable from Adsterra account → API Keys).
 * Save the key via the form on this page; it is stored in config/adsterra.local.php.
 */

require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_metrics.php';

// ── Local config ─────────────────────────────────────────────────────────────
$localCfg = __DIR__ . '/../config/adsterra.local.php';
if (is_file($localCfg)) require_once $localCfg;
if (!defined('ADSTERRA_API_KEY')) define('ADSTERRA_API_KEY', '');

// ── Ad zone definitions (same keys as includes/ads.php) ─────────────────────
$adZones = [
    'e6b14c0b1e23d50b7cc854ab945d75d2' => '300×250 Rectangle',
    '3b7ca9fe5e27e40425e7d54b722e0c9b' => '728×90 Leaderboard',
    'c9ab950e78bcfd111d5ef395b7c3db32' => '468×60 Standard Banner',
    'b8a76cdfb00943ce4df530532324a570' => '160×600 Wide Skyscraper',
    '70a277bc726718d70c4c9c357bb406e4' => '320×50 Mobile Banner',
    'd4e1d4d09336216b9e711a6281ef7039' => '160×300 Small Rectangle',
    '432d607d772e51993d224923217541cc' => 'Social Bar',
];

// ── Process form: save API key ───────────────────────────────────────────────
$flash     = '';
$flashType = 'success';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_api_key'])) {
    verifyCsrf();
    $apiKey = trim($_POST['adsterra_api_key'] ?? '');
    if ($apiKey !== '' && !preg_match('/^[a-f0-9\-]{20,80}$/i', $apiKey)) {
        $flash     = 'API key format looks invalid. Please paste the key exactly from Adsterra.';
        $flashType = 'error';
    } else {
        $php  = "<?php\n";
        $php .= "// Generated by /admin/adsterra.php — do not edit manually\n";
        $php .= "define('ADSTERRA_API_KEY', " . var_export($apiKey, true) . ");\n";
        file_put_contents($localCfg, $php, LOCK_EX);
        if (!defined('ADSTERRA_API_KEY')) define('ADSTERRA_API_KEY', $apiKey);
        $flash = $apiKey === '' ? 'API key cleared.' : 'API key saved.';
    }
}

// ── Date range for stats request ─────────────────────────────────────────────
$dateFrom = $_GET['from'] ?? date('Y-m-d', strtotime('-7 days'));
$dateTo   = $_GET['to']   ?? date('Y-m-d');

// Clamp to sane values
$dateFrom = preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateFrom) ? $dateFrom : date('Y-m-d', strtotime('-7 days'));
$dateTo   = preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateTo)   ? $dateTo   : date('Y-m-d');

// ── Fetch stats from Adsterra API ────────────────────────────────────────────
$stats       = [];
$statsError  = '';
$apiRawBody  = '';
$apiKey      = defined('ADSTERRA_API_KEY') ? ADSTERRA_API_KEY : '';

/**
 * vdj_adsterra_fetch — Calls Adsterra Publisher API v3.
 *
 * Endpoint: GET https://api3.adsterra.com/v3/publisher/statistic
 * Auth:     Bearer token in Authorization header
 * Params:   date_from, date_to, group_by (optional: date/place_id/os/country…)
 *
 * Returns decoded array or throws RuntimeException on failure.
 */
function vdj_adsterra_fetch(string $apiKey, string $from, string $to, string $groupBy = 'date'): array {
    if ($apiKey === '') throw new RuntimeException('No API key configured. Add your Adsterra Publisher API key below.');

    $url = 'https://api3.adsterra.com/v3/publisher/statistic?' . http_build_query([
        'date_from' => $from,
        'date_to'   => $to,
        'group_by'  => $groupBy,
    ]);

    $ctx = stream_context_create([
        'http' => [
            'method'  => 'GET',
            'header'  => "Authorization: Bearer {$apiKey}\r\nAccept: application/json\r\n",
            'timeout' => 15,
            'ignore_errors' => true,
        ],
        'ssl' => [
            'verify_peer'      => true,
            'verify_peer_name' => true,
        ],
    ]);

    $raw = @file_get_contents($url, false, $ctx);
    if ($raw === false) {
        throw new RuntimeException('Could not reach Adsterra API. Check your server\'s outbound HTTPS access.');
    }

    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        throw new RuntimeException('Unexpected response from Adsterra API: ' . substr($raw, 0, 200));
    }
    if (isset($decoded['error'])) {
        throw new RuntimeException('Adsterra API error: ' . $decoded['error']);
    }
    if (isset($decoded['message']) && !isset($decoded['data'])) {
        throw new RuntimeException('Adsterra API: ' . $decoded['message']);
    }

    return $decoded;
}

// Only call API when a key is configured
if ($apiKey !== '') {
    $groupBy = in_array($_GET['group_by'] ?? 'date', ['date', 'place_id', 'os', 'country', 'device'], true)
        ? $_GET['group_by']
        : 'date';
    try {
        $rawStats   = vdj_adsterra_fetch($apiKey, $dateFrom, $dateTo, $groupBy);
        $stats      = $rawStats['data'] ?? $rawStats; // v3 wraps rows in "data" key
        $statsError = '';
    } catch (Throwable $e) {
        $statsError = $e->getMessage();
    }
}

// ── Totals row ───────────────────────────────────────────────────────────────
$totals = ['impressions' => 0, 'clicks' => 0, 'cpm' => 0, 'revenue' => 0, '_cpm_rows' => 0];
foreach ($stats as $row) {
    $totals['impressions'] += (int)($row['impressions'] ?? $row['views'] ?? 0);
    $totals['clicks']      += (int)($row['clicks'] ?? 0);
    $totals['revenue']     += (float)($row['revenue'] ?? $row['earnings'] ?? 0);
    if (!empty($row['cpm'])) {
        $totals['cpm'] += (float)$row['cpm'];
        $totals['_cpm_rows']++;
    }
}
$totals['cpm_avg'] = $totals['_cpm_rows'] > 0 ? $totals['cpm'] / $totals['_cpm_rows'] : 0;
$totalCtr = $totals['impressions'] > 0 ? round($totals['clicks'] / $totals['impressions'] * 100, 2) : 0;

// ── Page vars ─────────────────────────────────────────────────────────────────
$csrf        = csrfToken();
$currentPage = 'adsterra';
$currentApiKey = ADSTERRA_API_KEY;
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Adsterra Stats — Admin</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <link rel="stylesheet" href="/admin/admin.css">
  <style>
    /* ── Summary metric cards ── */
    .at-summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 16px; margin-bottom: 28px; }
    .at-metric { background:#fff; border:1px solid var(--border); border-radius:12px; padding:20px 18px; display:flex; flex-direction:column; gap:4px; }
    .at-metric__label { font-size:12px; font-weight:600; text-transform:uppercase; letter-spacing:.08em; color:var(--text-muted); }
    .at-metric__value { font-size:26px; font-weight:700; font-family:'Manrope',sans-serif; color:var(--text); line-height:1.1; }
    .at-metric__sub { font-size:12px; color:var(--text-muted); }
    .at-metric--revenue .at-metric__value { color:#16a34a; }
    .at-metric--cpm .at-metric__value { color:#7f77dd; }

    /* ── Filters bar ── */
    .at-filters { display:flex; flex-wrap:wrap; gap:10px; align-items:center; margin-bottom:24px; }
    .at-filters input[type="date"] { border:1px solid var(--border); border-radius:8px; padding:8px 10px; font-size:13px; color:var(--text); }
    .at-filters select { border:1px solid var(--border); border-radius:8px; padding:8px 10px; font-size:13px; color:var(--text); background:#fff; }

    /* ── Stats table ── */
    .at-table-wrap { overflow-x:auto; }
    .at-table { width:100%; border-collapse:collapse; font-size:13px; }
    .at-table th { background:var(--surface,#f8f9fa); color:var(--text-muted); font-size:11px; font-weight:600; text-transform:uppercase; letter-spacing:.07em; padding:10px 12px; border-bottom:1px solid var(--border); text-align:left; white-space:nowrap; }
    .at-table td { padding:11px 12px; border-bottom:1px solid var(--border); color:var(--text); vertical-align:middle; }
    .at-table tr:last-child td { border-bottom:none; }
    .at-table tr:hover td { background:rgba(127,119,221,.04); }
    .at-table .num { text-align:right; font-variant-numeric:tabular-nums; }
    .at-table tfoot td { font-weight:700; background:var(--surface,#f8f9fa); }
    .rev { color:#16a34a; font-weight:700; }

    /* ── API key form ── */
    .at-key-form { display:flex; gap:10px; align-items:center; flex-wrap:wrap; }
    .at-key-form input[type="text"] { flex:1; min-width:280px; border:1px solid var(--border); border-radius:8px; padding:10px 12px; font-size:14px; font-family:monospace; }

    /* ── Zone chips ── */
    .at-zones { display:flex; flex-wrap:wrap; gap:8px; }
    .at-zone-chip { display:inline-flex; align-items:center; gap:6px; background:#f1f0fd; border:1px solid #d4d2f9; border-radius:6px; padding:5px 10px; font-size:12px; font-weight:600; color:#5a54c4; }

    /* ── Empty state ── */
    .at-empty { text-align:center; padding:60px 20px; color:var(--text-muted); }
    .at-empty i { font-size:40px; margin-bottom:14px; opacity:.35; display:block; }
    .at-empty h3 { margin:0 0 8px; font-size:18px; color:var(--text); }

    /* ── Quick date presets ── */
    .at-presets { display:flex; flex-wrap:wrap; gap:6px; }
    .at-preset { border:1px solid var(--border); border-radius:6px; padding:5px 10px; font-size:12px; font-weight:600; color:var(--text-muted); cursor:pointer; background:#fff; transition:all .15s; }
    .at-preset:hover { border-color:#7f77dd; color:#7f77dd; }
  </style>
</head>
<body>
<?php require_once __DIR__ . '/_sidebar.php'; ?>
<main class="admin-main">
  <div class="admin-topbar">
    <div class="admin-header">
      <h1><i class="fa-solid fa-rectangle-ad" style="color:#7f77dd;margin-right:8px;"></i>Adsterra Statistics</h1>
      <p>Publisher API stats — impressions, clicks, CPM and revenue across your ad zones.</p>
    </div>
    <button class="hamburger" id="hamburger"><i class="fa-solid fa-bars"></i></button>
  </div>

  <?php if ($flash): ?>
    <div class="flash flash-<?= $flashType === 'error' ? 'error' : 'success' ?>"><?= e($flash) ?></div>
  <?php endif; ?>

  <!-- ── API Key Config ───────────────────────────────────────────────────── -->
  <div class="admin-card" style="margin-bottom:24px;">
    <div class="admin-card__header">
      <h2><i class="fa-solid fa-key"></i> API Key</h2>
    </div>
    <div class="admin-card__body">
      <p style="font-size:13px;color:var(--text-muted);margin:0 0 14px;">
        Get your Publisher API key from
        <a href="https://publishers.adsterra.com/profile/api" target="_blank" rel="noopener" style="color:#7f77dd;">
          Adsterra → Profile → API Keys
        </a>. The key is stored locally in <code>config/adsterra.local.php</code> — never committed to git.
      </p>
      <form method="post" action="/admin/adsterra.php" class="at-key-form">
        <input type="hidden" name="csrf_token" value="<?= e($csrf) ?>">
        <input type="text"
               name="adsterra_api_key"
               placeholder="Paste your Adsterra Publisher API key…"
               value="<?= e($currentApiKey ? str_repeat('•', min(strlen($currentApiKey), 20)) . substr($currentApiKey, -4) : '') ?>"
               autocomplete="off"
               spellcheck="false">
        <button type="submit" name="save_api_key" value="1" class="btn btn-primary">
          <i class="fa-solid fa-floppy-disk"></i> Save Key
        </button>
        <?php if ($currentApiKey): ?>
          <span style="font-size:12px;color:#16a34a;font-weight:600;">
            <i class="fa-solid fa-circle-check"></i> Key configured
          </span>
        <?php endif; ?>
      </form>
    </div>
  </div>

  <!-- ── Active Ad Zones ──────────────────────────────────────────────────── -->
  <div class="admin-card" style="margin-bottom:24px;">
    <div class="admin-card__header">
      <h2><i class="fa-solid fa-layer-group"></i> Active Ad Zones</h2>
    </div>
    <div class="admin-card__body">
      <div class="at-zones">
        <?php foreach ($adZones as $key => $label): ?>
          <span class="at-zone-chip">
            <i class="fa-solid fa-square-check"></i>
            <?= e($label) ?>
            <span style="font-family:monospace;opacity:.6;font-weight:400;"><?= e(substr($key, 0, 8)) ?>…</span>
          </span>
        <?php endforeach; ?>
      </div>
      <p style="font-size:12px;color:var(--text-muted);margin:12px 0 0;">
        7 zones active — all rendering via <code>includes/ads.php</code>. Zone-level breakdown is available via group_by=place_id (requires Adsterra to map zone IDs to keys).
      </p>
    </div>
  </div>

  <!-- ── Date filter + Group by ────────────────────────────────────────────── -->
  <form method="GET" action="/admin/adsterra.php" id="filterForm">
    <div class="admin-card" style="margin-bottom:24px;">
      <div class="admin-card__header">
        <h2><i class="fa-solid fa-sliders"></i> Date Range &amp; Grouping</h2>
      </div>
      <div class="admin-card__body">
        <div class="at-filters">
          <label style="display:flex;flex-direction:column;gap:4px;font-size:12px;font-weight:600;color:var(--text-muted);">
            From
            <input type="date" name="from" value="<?= e($dateFrom) ?>" max="<?= date('Y-m-d') ?>">
          </label>
          <label style="display:flex;flex-direction:column;gap:4px;font-size:12px;font-weight:600;color:var(--text-muted);">
            To
            <input type="date" name="to" value="<?= e($dateTo) ?>" max="<?= date('Y-m-d') ?>">
          </label>
          <label style="display:flex;flex-direction:column;gap:4px;font-size:12px;font-weight:600;color:var(--text-muted);">
            Group by
            <select name="group_by">
              <?php foreach (['date'=>'Date','place_id'=>'Ad Zone','os'=>'OS','country'=>'Country','device'=>'Device'] as $val=>$lbl): ?>
                <option value="<?= e($val) ?>" <?= (($_GET['group_by'] ?? 'date') === $val) ? 'selected' : '' ?>><?= e($lbl) ?></option>
              <?php endforeach; ?>
            </select>
          </label>
          <button type="submit" class="btn btn-primary" style="align-self:flex-end;">
            <i class="fa-solid fa-chart-line"></i> Load Stats
          </button>
        </div>
        <!-- Quick presets -->
        <div class="at-presets" style="margin-top:12px;">
          <?php
          $presets = [
            'Today'      => [date('Y-m-d'), date('Y-m-d')],
            'Yesterday'  => [date('Y-m-d', strtotime('-1 day')), date('Y-m-d', strtotime('-1 day'))],
            'Last 7 days'=> [date('Y-m-d', strtotime('-7 days')), date('Y-m-d')],
            'Last 30 days'=> [date('Y-m-d', strtotime('-30 days')), date('Y-m-d')],
            'This month' => [date('Y-m-01'), date('Y-m-d')],
          ];
          foreach ($presets as $label => [$from, $to]):
          ?>
            <button type="button" class="at-preset"
                    onclick="document.querySelector('[name=from]').value='<?= e($from) ?>';document.querySelector('[name=to]').value='<?= e($to) ?>';document.getElementById('filterForm').submit();">
              <?= e($label) ?>
            </button>
          <?php endforeach; ?>
        </div>
      </div>
    </div>
  </form>

  <!-- ── Summary metrics ───────────────────────────────────────────────────── -->
  <?php if (!empty($stats)): ?>
  <div class="at-summary">
    <div class="at-metric">
      <span class="at-metric__label">Impressions</span>
      <span class="at-metric__value"><?= number_format($totals['impressions']) ?></span>
      <span class="at-metric__sub"><?= e($dateFrom) ?> → <?= e($dateTo) ?></span>
    </div>
    <div class="at-metric">
      <span class="at-metric__label">Clicks</span>
      <span class="at-metric__value"><?= number_format($totals['clicks']) ?></span>
      <span class="at-metric__sub">CTR <?= e($totalCtr) ?>%</span>
    </div>
    <div class="at-metric at-metric--cpm">
      <span class="at-metric__label">Avg CPM</span>
      <span class="at-metric__value">$<?= number_format($totals['cpm_avg'], 2) ?></span>
      <span class="at-metric__sub">Per 1,000 impressions</span>
    </div>
    <div class="at-metric at-metric--revenue">
      <span class="at-metric__label">Revenue</span>
      <span class="at-metric__value">$<?= number_format($totals['revenue'], 2) ?></span>
      <span class="at-metric__sub">Estimated earnings</span>
    </div>
  </div>
  <?php endif; ?>

  <!-- ── Stats table ───────────────────────────────────────────────────────── -->
  <div class="admin-card">
    <div class="admin-card__header">
      <h2><i class="fa-solid fa-table"></i> Breakdown by <?= e(ucfirst($_GET['group_by'] ?? 'date')) ?></h2>
    </div>
    <div class="admin-card__body">

      <?php if (!$apiKey): ?>
        <div class="at-empty">
          <i class="fa-solid fa-key"></i>
          <h3>API key not configured</h3>
          <p>Paste your Adsterra Publisher API key above to start fetching live stats.</p>
        </div>

      <?php elseif ($statsError): ?>
        <div class="flash flash-error" style="margin-bottom:0;">
          <i class="fa-solid fa-triangle-exclamation"></i>
          <strong>API Error:</strong> <?= e($statsError) ?>
        </div>
        <p style="font-size:12px;color:var(--text-muted);margin-top:12px;">
          Common causes: invalid/expired API key, no data for the selected range, or API rate limit.
          <a href="https://kb.adsterra.com/article/127-publisher-api-overview" target="_blank" rel="noopener" style="color:#7f77dd;">API docs →</a>
        </p>

      <?php elseif (empty($stats)): ?>
        <div class="at-empty">
          <i class="fa-solid fa-chart-bar"></i>
          <h3>No data for this period</h3>
          <p>Try a wider date range, or check that your zones are serving impressions.</p>
        </div>

      <?php else: ?>
        <!-- Determine columns dynamically from first row -->
        <?php
        $firstRow = reset($stats);
        $knownCols = [
          'date'        => 'Date',
          'place_id'    => 'Zone ID',
          'country'     => 'Country',
          'os'          => 'OS',
          'device'      => 'Device',
          'impressions' => 'Impressions',
          'views'       => 'Views',
          'clicks'      => 'Clicks',
          'cpm'         => 'CPM ($)',
          'ctr'         => 'CTR (%)',
          'revenue'     => 'Revenue ($)',
          'earnings'    => 'Earnings ($)',
        ];
        $cols = array_filter($knownCols, fn($k) => array_key_exists($k, $firstRow), ARRAY_FILTER_USE_KEY);
        $numericCols = ['impressions','views','clicks','cpm','ctr','revenue','earnings'];
        ?>
        <div class="at-table-wrap">
          <table class="at-table">
            <thead>
              <tr>
                <?php foreach ($cols as $key => $label): ?>
                  <th class="<?= in_array($key, $numericCols, true) ? 'num' : '' ?>"><?= e($label) ?></th>
                <?php endforeach; ?>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($stats as $row): ?>
                <tr>
                  <?php foreach ($cols as $key => $_): ?>
                    <?php
                    $val = $row[$key] ?? '—';
                    $isNum = in_array($key, $numericCols, true);
                    $isRev = in_array($key, ['revenue','earnings'], true);
                    if ($isRev && is_numeric($val)) $val = '$' . number_format((float)$val, 2);
                    elseif ($key === 'cpm' && is_numeric($val)) $val = '$' . number_format((float)$val, 2);
                    elseif ($key === 'ctr' && is_numeric($val)) $val = number_format((float)$val, 2) . '%';
                    elseif ($isNum && is_numeric($val)) $val = number_format((int)$val);
                    ?>
                    <td class="<?= $isNum ? 'num' : '' ?> <?= $isRev ? 'rev' : '' ?>"><?= e((string)$val) ?></td>
                  <?php endforeach; ?>
                </tr>
              <?php endforeach; ?>
            </tbody>
            <?php if (!empty($stats) && count($stats) > 1): ?>
            <tfoot>
              <tr>
                <?php $first = true; foreach ($cols as $key => $_): ?>
                  <?php if ($first): $first = false; ?>
                    <td>Totals</td>
                  <?php elseif ($key === 'impressions' || $key === 'views'): ?>
                    <td class="num"><?= number_format($totals['impressions']) ?></td>
                  <?php elseif ($key === 'clicks'): ?>
                    <td class="num"><?= number_format($totals['clicks']) ?></td>
                  <?php elseif ($key === 'cpm'): ?>
                    <td class="num">$<?= number_format($totals['cpm_avg'], 2) ?> avg</td>
                  <?php elseif ($key === 'ctr'): ?>
                    <td class="num"><?= e($totalCtr) ?>%</td>
                  <?php elseif ($key === 'revenue' || $key === 'earnings'): ?>
                    <td class="num rev">$<?= number_format($totals['revenue'], 2) ?></td>
                  <?php else: ?>
                    <td></td>
                  <?php endif; ?>
                <?php endforeach; ?>
              </tr>
            </tfoot>
            <?php endif; ?>
          </table>
        </div>

        <p style="font-size:11px;color:var(--text-muted);margin:14px 0 0;">
          <?= count($stats) ?> row(s) returned ·
          Data from Adsterra Publisher API v3 ·
          Refreshed on page load · Revenue figures are estimates until finalized by Adsterra.
        </p>
      <?php endif; ?>

    </div>
  </div>

</main>
</body>
</html>
