<?php
// FILE: admin/analytics.php
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/../includes/ga4.php';

// ── GA4 config save ────────────────────────────────────────────────────────
$ga4Flash     = '';
$ga4FlashType = 'success';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['ga4_action'])) {
    verifyCsrf();

    if ($_POST['ga4_action'] === 'save_config') {
        $propId       = preg_replace('/[^0-9]/', '', trim($_POST['ga4_property_id'] ?? ''));
        $clientId     = trim($_POST['ga4_client_id'] ?? '');
        $clientSecretRaw = trim($_POST['ga4_client_secret'] ?? '');
        // Ignore placeholder mask (bullets mean "unchanged")
        $clientSecret = preg_match('/^[•]+$/', $clientSecretRaw) ? '' : $clientSecretRaw;

        if ($propId === '') {
            $ga4Flash = 'Property ID must be numeric (e.g. 123456789).';
            $ga4FlashType = 'error';
        } else {
            $php  = "<?php\n// Generated by /admin/analytics.php\n";
            $php .= "define('GA4_PROPERTY_ID', " . var_export($propId, true) . ");\n";
            // Preserve existing values if fields were left blank/masked
            $saveClientId     = $clientId     ?: GA4_OAUTH_CLIENT_ID;
            $saveClientSecret = $clientSecret ?: GA4_OAUTH_CLIENT_SECRET;
            if ($saveClientId)     $php .= "define('GA4_OAUTH_CLIENT_ID', " . var_export($saveClientId, true) . ");\n";
            if ($saveClientSecret) $php .= "define('GA4_OAUTH_CLIENT_SECRET', " . var_export($saveClientSecret, true) . ");\n";
            file_put_contents(GA4_CFG_FILE, $php, LOCK_EX);
            // Reload constants
            if (!defined('GA4_PROPERTY_ID'))         define('GA4_PROPERTY_ID', $propId);
            if ($clientId && !defined('GA4_OAUTH_CLIENT_ID'))         define('GA4_OAUTH_CLIENT_ID', $clientId);
            if ($clientSecret && !defined('GA4_OAUTH_CLIENT_SECRET')) define('GA4_OAUTH_CLIENT_SECRET', $clientSecret);
            $ga4Flash = 'Settings saved.';
        }
    }

    if ($_POST['ga4_action'] === 'disconnect_oauth') {
        if (is_file(GA4_OAUTH_FILE)) unlink(GA4_OAUTH_FILE);
        foreach (glob(GA4_CACHE_DIR . '/ga4-*.json') ?: [] as $f) unlink($f);
        $ga4Flash = 'Google account disconnected.';
    }

    if ($_POST['ga4_action'] === 'clear_cache') {
        foreach (glob(GA4_CACHE_DIR . '/ga4-*.json') ?: [] as $f) unlink($f);
        $ga4Flash = 'GA4 cache cleared.';
    }
}

// ── Fetch GA4 data ─────────────────────────────────────────────────────────
$ga4Data  = null;
$ga4Error = '';
if (vdj_ga4_ready()) {
    try {
        $ga4Data = vdj_ga4_dashboard_data();
    } catch (Throwable $e) {
        $ga4Error = $e->getMessage();
    }
}
$ga4CsrfToken = csrfToken();

// ── Users per day last 30 days ─────────────────────────────────────────────
$usersByDay = $db->query(
    "SELECT DATE(created_at) AS d, COUNT(*) AS cnt
     FROM users
     WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
     GROUP BY DATE(created_at)
     ORDER BY d ASC"
)->fetchAll(PDO::FETCH_ASSOC);

// ── Boards per day last 30 days ────────────────────────────────────────────
$boardsByDay = $db->query(
    "SELECT DATE(created_at) AS d, COUNT(*) AS cnt
     FROM boards
     WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
     GROUP BY DATE(created_at)
     ORDER BY d ASC"
)->fetchAll(PDO::FETCH_ASSOC);

// Fill in all 30 days so chart has no gaps
function fillDays(array $rows, int $days = 30): array {
    $map = [];
    foreach ($rows as $row) {
        $map[$row['d']] = (int)$row['cnt'];
    }
    $result = [];
    for ($i = $days - 1; $i >= 0; $i--) {
        $date = date('Y-m-d', strtotime("-{$i} days"));
        $result[] = ['d' => $date, 'cnt' => $map[$date] ?? 0];
    }
    return $result;
}
$usersByDay  = fillDays($usersByDay);
$boardsByDay = fillDays($boardsByDay);

$userDayLabels  = array_column($usersByDay,  'd');
$userDayCounts  = array_column($usersByDay,  'cnt');
$boardDayLabels = array_column($boardsByDay, 'd');
$boardDayCounts = array_column($boardsByDay, 'cnt');

// ── Top 10 boards by likes ─────────────────────────────────────────────────
$topBoardsLikes = $db->query(
    "SELECT b.title, b.id, u.username,
            COUNT(bl.id) AS likes
     FROM boards b
     JOIN users u ON u.id = b.user_id
     LEFT JOIN board_likes bl ON bl.board_id = b.id
     WHERE b.is_draft = 0
     GROUP BY b.id, b.title, u.username
     ORDER BY likes DESC
     LIMIT 10"
)->fetchAll(PDO::FETCH_ASSOC);

$topBoardLabels = array_map(function($b) {
    $label = $b['title'];
    return mb_strlen($label) > 30 ? mb_substr($label, 0, 27) . '...' : $label;
}, $topBoardsLikes);
$topBoardCounts = array_column($topBoardsLikes, 'likes');

// ── Top 5 style tags ───────────────────────────────────────────────────────
$allTags = $db->query(
    "SELECT style_tags FROM boards WHERE style_tags IS NOT NULL AND style_tags != ''"
)->fetchAll(PDO::FETCH_COLUMN);

$tagCounts = [];
foreach ($allTags as $tagStr) {
    $tags = array_map('trim', explode(',', $tagStr));
    foreach ($tags as $tag) {
        if ($tag !== '') {
            $tagCounts[$tag] = ($tagCounts[$tag] ?? 0) + 1;
        }
    }
}
arsort($tagCounts);
$topTags = array_slice($tagCounts, 0, 8, true);
$tagLabels = array_keys($topTags);
$tagValues = array_values($topTags);

// ── Board status: published vs draft ──────────────────────────────────────
$publishedCount = (int)$db->query("SELECT COUNT(*) FROM boards WHERE is_draft = 0")->fetchColumn();
$draftCount     = (int)$db->query("SELECT COUNT(*) FROM boards WHERE is_draft = 1")->fetchColumn();

// ── User breakdown: admins vs regular ─────────────────────────────────────
$totalUsers    = (int)$db->query("SELECT COUNT(*) FROM users")->fetchColumn();
$adminCount    = (int)$db->query("SELECT COUNT(*) FROM users WHERE is_admin = 1")->fetchColumn();
$regularCount  = $totalUsers - $adminCount;

// ── Summary counts ─────────────────────────────────────────────────────────
$totalBoards = (int)$db->query("SELECT COUNT(*) FROM boards")->fetchColumn();
$totalLikes  = (int)$db->query("SELECT COUNT(*) FROM board_likes")->fetchColumn();

// ── Sponsor lead funnel ────────────────────────────────────────────────────
$sponsorStats = [];
try {
    $rows = $db->query("SELECT status, COUNT(*) AS cnt FROM sponsor_leads GROUP BY status")->fetchAll(PDO::FETCH_KEY_PAIR);
    $sponsorStats = [
        'total'      => array_sum($rows),
        'new'        => (int)($rows['new']        ?? 0),
        'contacted'  => (int)($rows['contacted']  ?? 0),
        'won'        => (int)($rows['won']         ?? 0),
        'lost'       => (int)($rows['lost']        ?? 0),
    ];
    // Win rate
    $closed = $sponsorStats['won'] + $sponsorStats['lost'];
    $sponsorStats['win_rate'] = $closed > 0 ? round($sponsorStats['won'] / $closed * 100) : 0;
} catch (Throwable $e) { $sponsorStats = ['total'=>0,'new'=>0,'contacted'=>0,'won'=>0,'lost'=>0,'win_rate'=>0]; }

// ── Newsletter growth last 30 days ─────────────────────────────────────────
$newsletterStats = ['total' => 0, 'active' => 0];
try {
    $row = $db->query("SELECT COUNT(*) AS total, SUM(status='active') AS active FROM newsletter_subscribers")->fetch();
    $newsletterStats = ['total' => (int)$row['total'], 'active' => (int)$row['active']];
} catch (Throwable $e) {}

// ── Traffic: page views last 30 days ──────────────────────────────────────
$trafficStats  = ['total' => 0, 'guests' => 0, 'registered' => 0, 'unique' => 0];
$viewsByDay    = fillDays([]);
$topPages      = [];
$deviceBreak   = ['desktop' => 0, 'mobile' => 0, 'tablet' => 0];
$topReferrers  = [];
$hasTraffic    = false;
try {
    $row = $db->query(
        "SELECT COUNT(*) AS total,
                SUM(is_guest = 1)  AS guests,
                SUM(is_guest = 0)  AS registered,
                COUNT(DISTINCT visitor_hash) AS unique_visitors
         FROM page_views
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)"
    )->fetch(PDO::FETCH_ASSOC);
    $trafficStats = [
        'total'      => (int)$row['total'],
        'guests'     => (int)$row['guests'],
        'registered' => (int)$row['registered'],
        'unique'     => (int)$row['unique_visitors'],
    ];
    $hasTraffic = $trafficStats['total'] > 0;

    // Views per day split guest/registered
    $viewsRaw = $db->query(
        "SELECT DATE(created_at) AS d,
                SUM(is_guest = 1) AS guests,
                SUM(is_guest = 0) AS registered
         FROM page_views
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY DATE(created_at)
         ORDER BY d ASC"
    )->fetchAll(PDO::FETCH_ASSOC);
    $guestMap = []; $regMap = [];
    foreach ($viewsRaw as $r) { $guestMap[$r['d']] = (int)$r['guests']; $regMap[$r['d']] = (int)$r['registered']; }
    $viewsByDay = [];
    for ($i = 29; $i >= 0; $i--) {
        $date = date('Y-m-d', strtotime("-{$i} days"));
        $viewsByDay[] = ['d' => $date, 'guests' => $guestMap[$date] ?? 0, 'registered' => $regMap[$date] ?? 0];
    }

    // Top 10 pages
    $topPages = $db->query(
        "SELECT page_path, page_title, COUNT(*) AS views, COUNT(DISTINCT visitor_hash) AS uniques
         FROM page_views
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY page_path, page_title
         ORDER BY views DESC
         LIMIT 10"
    )->fetchAll(PDO::FETCH_ASSOC);

    // Device breakdown
    $devRows = $db->query(
        "SELECT device_type, COUNT(*) AS cnt FROM page_views
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY device_type"
    )->fetchAll(PDO::FETCH_KEY_PAIR);
    $deviceBreak = [
        'desktop' => (int)($devRows['desktop'] ?? 0),
        'mobile'  => (int)($devRows['mobile']  ?? 0),
        'tablet'  => (int)($devRows['tablet']  ?? 0),
    ];

    // Top referrers (exclude empty)
    $topReferrers = $db->query(
        "SELECT referrer, COUNT(*) AS cnt FROM page_views
         WHERE referrer IS NOT NULL AND referrer != ''
           AND created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY referrer
         ORDER BY cnt DESC
         LIMIT 8"
    )->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) {}

// ── Board Clicks last 30 days ─────────────────────────────────────────────
$clickStats   = ['total' => 0, 'guests' => 0, 'registered' => 0];
$topClickedBoards = [];
$clicksBySource   = [];
$hasClicks    = false;
try {
    $crow = $db->query(
        "SELECT COUNT(*) AS total,
                SUM(is_guest=1) AS guests,
                SUM(is_guest=0) AS registered
         FROM board_clicks
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)"
    )->fetch(PDO::FETCH_ASSOC);
    $clickStats = [
        'total'      => (int)$crow['total'],
        'guests'     => (int)$crow['guests'],
        'registered' => (int)$crow['registered'],
    ];
    $hasClicks = $clickStats['total'] > 0;

    // Top 10 clicked boards
    $topClickedBoards = $db->query(
        "SELECT bc.board_id, b.title, COUNT(*) AS clicks, b.view_count,
                (SELECT COUNT(*) FROM board_likes bl WHERE bl.board_id = bc.board_id) AS likes
         FROM board_clicks bc
         JOIN boards b ON b.id = bc.board_id
         WHERE bc.created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY bc.board_id, b.title, b.view_count
         ORDER BY clicks DESC
         LIMIT 10"
    )->fetchAll(PDO::FETCH_ASSOC);

    // Clicks by source
    $srcRows = $db->query(
        "SELECT click_source, COUNT(*) AS cnt FROM board_clicks
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY click_source"
    )->fetchAll(PDO::FETCH_KEY_PAIR);
    $clicksBySource = $srcRows ?: [];
} catch (Throwable $e) {}

// ── Top 10 most-followed curators ─────────────────────────────────────────
$topFollowed = [];
try {
    $topFollowed = $db->query(
        "SELECT u.username, u.avatar, u.is_verified,
                COUNT(f.follower_id) AS follower_count
         FROM users u
         LEFT JOIN follows f ON f.following_id = u.id
         GROUP BY u.id, u.username, u.avatar, u.is_verified
         ORDER BY follower_count DESC
         LIMIT 10"
    )->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) { $topFollowed = []; }

// ── Follow activity last 30 days ──────────────────────────────────────────
$followsByDay = [];
try {
    $followsByDay = fillDays($db->query(
        "SELECT DATE(created_at) AS d, COUNT(*) AS cnt
         FROM follows
         WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
         GROUP BY DATE(created_at)
         ORDER BY d ASC"
    )->fetchAll(PDO::FETCH_ASSOC));
} catch (Throwable $e) { $followsByDay = fillDays([]); }

$followDayLabels = array_column($followsByDay, 'd');
$followDayCounts = array_column($followsByDay, 'cnt');

$currentPage = 'analytics';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analytics — Admin — Visual Design Journey</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="/admin/admin.css">
    <style>
        .analytics-summary {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 16px;
            margin-bottom: 28px;
        }
        .analytics-two-col {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 28px;
        }
        .user-breakdown-stat {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 14px 20px;
            border-bottom: 1px solid #f1f5f9;
        }
        .user-breakdown-stat:last-child { border-bottom: none; }
        .user-breakdown-stat .label { font-size: 14px; color: var(--text); display: flex; align-items: center; gap: 10px; }
        .user-breakdown-stat .value { font-size: 18px; font-weight: 700; font-family: 'Manrope', sans-serif; color: var(--text); }
        .breakdown-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            display: inline-block;
        }
        @media (max-width: 1024px) {
            .analytics-summary { grid-template-columns: 1fr 1fr; }
            .analytics-two-col { grid-template-columns: 1fr; }
        }
        @media (max-width: 480px) {
            .analytics-summary { grid-template-columns: 1fr; }
        }
        /* ── Revenue Analytics ─────────────────────────────────────────── */
        .revenue-funnel-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 12px;
            padding: 0 20px 20px;
        }
        .funnel-stat {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 6px;
            padding: 14px 10px;
            border-radius: 10px;
            background: #f8fafc;
        }
        .funnel-stat__icon {
            font-size: 18px;
        }
        .funnel-stat__num {
            font-size: 22px;
            font-weight: 700;
            font-family: 'Manrope', sans-serif;
        }
        .funnel-stat__label {
            font-size: 11px;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: .04em;
        }
        .revenue-win-rate {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 12px 20px 20px;
        }
        .win-rate-badge {
            font-size: 28px;
            font-weight: 700;
            font-family: 'Manrope', sans-serif;
            color: #22c55e;
        }
        .win-rate-label {
            font-size: 13px;
            color: var(--text-muted);
            line-height: 1.4;
        }
        .revenue-card-footer {
            padding: 12px 20px;
            border-top: 1px solid #f1f5f9;
            font-size: 13px;
        }
        .newsletter-stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 12px;
            padding: 0 20px 20px;
        }
        .newsletter-stat {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 6px;
            padding: 14px 10px;
            border-radius: 10px;
            background: #f8fafc;
        }
        .newsletter-stat__num {
            font-size: 26px;
            font-weight: 700;
            font-family: 'Manrope', sans-serif;
        }
        .newsletter-stat__label {
            font-size: 11px;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: .04em;
        }
        @media (max-width: 640px) {
            .revenue-funnel-grid { grid-template-columns: repeat(2, 1fr); }
            .newsletter-stats-grid { grid-template-columns: repeat(2, 1fr); }
        }
        /* ── Follow Analytics ──────────────────────────────────────────── */
        .top-followed-list {
            list-style: none;
            margin: 0;
            padding: 0;
        }
        .top-followed-item {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 10px 20px;
            border-bottom: 1px solid #f1f5f9;
        }
        .top-followed-item:last-child { border-bottom: none; }
        .top-followed-rank {
            font-size: 13px;
            font-weight: 700;
            color: var(--text-muted);
            width: 22px;
            flex-shrink: 0;
            text-align: right;
        }
        .top-followed-username {
            flex: 1;
            font-size: 14px;
            font-weight: 500;
            color: var(--text);
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 6px;
        }
        .top-followed-username:hover { color: var(--accent); }
        .top-followed-count {
            font-size: 14px;
            font-weight: 700;
            font-family: 'Manrope', sans-serif;
            color: #8b5cf6;
        }
        .verified-badge {
            font-size: 12px;
            color: #3b82f6;
        }
    </style>
</head>
<body>

<?php require_once __DIR__ . '/_sidebar.php'; ?>

<main class="admin-main">

    <!-- Topbar -->
    <div class="admin-topbar">
        <div class="admin-header">
            <h1>Analytics</h1>
            <p>Growth metrics and platform insights for the last 30 days.</p>
        </div>
        <button class="hamburger" id="hamburger" aria-label="Toggle navigation">
            <i class="fa-solid fa-bars"></i>
        </button>
    </div>

    <?php if ($ga4Flash): ?>
    <div class="flash flash-<?= $ga4FlashType === 'error' ? 'error' : 'success' ?>"><?= e($ga4Flash) ?></div>
    <?php endif; ?>

    <!-- ══════════════════════════════════════════════════════════════════════
         GA4 SETUP + STATS
    ════════════════════════════════════════════════════════════════════════ -->
    <div id="ga4-setup" class="admin-card" style="margin-bottom:24px;">
        <div class="admin-card__header">
            <h2><i class="fa-brands fa-google" style="color:#ea4335;"></i> Google Analytics 4
                <?php if (vdj_ga4_ready()): ?>
                    <span style="background:#dcfce7;color:#166534;border-radius:999px;padding:2px 10px;font-size:11px;font-weight:700;margin-left:8px;">Configured</span>
                <?php else: ?>
                    <span style="background:#fef3c7;color:#92400e;border-radius:999px;padding:2px 10px;font-size:11px;font-weight:700;margin-left:8px;">Not set up</span>
                <?php endif; ?>
            </h2>
            <?php if (vdj_ga4_ready()): ?>
            <form method="post" style="margin:0;">
                <input type="hidden" name="csrf_token" value="<?= e($ga4CsrfToken) ?>">
                <input type="hidden" name="ga4_action" value="clear_cache">
                <button type="submit" class="btn btn-secondary btn-sm"><i class="fa-solid fa-rotate"></i> Clear cache</button>
            </form>
            <?php endif; ?>
        </div>
        <div class="admin-card__body">
            <details <?= !vdj_ga4_ready() ? 'open' : '' ?> style="margin-bottom:<?= vdj_ga4_ready() ? '0' : '20px' ?>;">
                <summary style="cursor:pointer;font-size:14px;font-weight:600;color:var(--text);list-style:none;display:flex;align-items:center;gap:8px;">
                    <i class="fa-solid fa-gear" style="color:#7f77dd;"></i>
                    <?= vdj_ga4_ready() ? 'Update credentials' : 'Connect GA4 (required)' ?>
                    <i class="fa-solid fa-chevron-down" style="font-size:11px;color:var(--text-muted);margin-left:auto;"></i>
                </summary>
                <div style="padding-top:16px;">
                    <!-- Step 1: Property ID + OAuth Client -->
                    <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:14px;font-size:13px;color:#92400e;margin-bottom:20px;line-height:1.7;">
                        <strong>Setup (2 minutes):</strong><br>
                        1. <a href="https://console.cloud.google.com/apis/library/analyticsdata.googleapis.com" target="_blank" rel="noopener" style="color:#7f77dd;">Enable Google Analytics Data API</a> in Google Cloud.<br>
                        2. Google Cloud → <strong>Credentials → Create OAuth 2.0 Client ID</strong> (Web Application type).<br>
                        &nbsp;&nbsp;&nbsp; Authorized redirect URI: <code style="background:#fef3c7;padding:1px 6px;border-radius:4px;">https://visualdesignjourney.com/admin/ga4-callback.php</code><br>
                        3. Copy the <strong>Client ID</strong> and <strong>Client Secret</strong> below.<br>
                        4. Find your <strong>Property ID</strong>: GA4 → Admin → Property Settings (just the number).
                    </div>

                    <form method="post" style="display:grid;gap:14px;max-width:560px;">
                        <input type="hidden" name="csrf_token" value="<?= e($ga4CsrfToken) ?>">
                        <input type="hidden" name="ga4_action" value="save_config">
                        <div>
                            <label style="display:block;font-size:13px;font-weight:600;margin-bottom:5px;">GA4 Property ID</label>
                            <input type="text" name="ga4_property_id"
                                   value="<?= e(GA4_PROPERTY_ID) ?>"
                                   placeholder="e.g. 123456789"
                                   style="width:100%;border:1px solid var(--border);border-radius:8px;padding:9px 12px;font-size:14px;font-family:monospace;">
                            <div style="font-size:12px;color:var(--text-muted);margin-top:3px;">GA4 → Admin → Property Settings → Property ID (numbers only)</div>
                        </div>
                        <div>
                            <label style="display:block;font-size:13px;font-weight:600;margin-bottom:5px;">OAuth2 Client ID</label>
                            <input type="text" name="ga4_client_id"
                                   value="<?= e(GA4_OAUTH_CLIENT_ID) ?>"
                                   placeholder="123456789-abc...apps.googleusercontent.com"
                                   style="width:100%;border:1px solid var(--border);border-radius:8px;padding:9px 12px;font-size:13px;font-family:monospace;">
                        </div>
                        <div>
                            <label style="display:block;font-size:13px;font-weight:600;margin-bottom:5px;">OAuth2 Client Secret</label>
                            <input type="password" name="ga4_client_secret"
                                   value="<?= GA4_OAUTH_CLIENT_SECRET ? str_repeat('•', 20) : '' ?>"
                                   placeholder="GOCSPX-..."
                                   style="width:100%;border:1px solid var(--border);border-radius:8px;padding:9px 12px;font-size:13px;font-family:monospace;"
                                   autocomplete="new-password">
                        </div>
                        <div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;">
                            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Save</button>
                            <?php if (GA4_OAUTH_CLIENT_ID && GA4_OAUTH_CLIENT_SECRET && GA4_PROPERTY_ID): ?>
                            <a href="<?= e(vdj_ga4_oauth_url()) ?>" class="btn btn-primary" style="background:#ea4335;">
                                <i class="fa-brands fa-google"></i>
                                <?= vdj_ga4_oauth_ready() ? 'Reconnect Google Account' : 'Connect Google Account' ?>
                            </a>
                            <?php endif; ?>
                            <?php if (vdj_ga4_oauth_ready()): ?>
                            <form method="post" style="margin:0;">
                                <input type="hidden" name="csrf_token" value="<?= e($ga4CsrfToken) ?>">
                                <input type="hidden" name="ga4_action" value="disconnect_oauth">
                                <button type="submit" class="btn btn-secondary" style="color:#ef4444;border-color:#fecaca;" onclick="return confirm('Disconnect Google account?')">
                                    <i class="fa-solid fa-unlink"></i> Disconnect
                                </button>
                            </form>
                            <?php endif; ?>
                        </div>
                    </form>

                    <?php if (vdj_ga4_oauth_ready()): ?>
                    <div style="margin-top:14px;display:flex;align-items:center;gap:8px;font-size:13px;color:#166534;">
                        <i class="fa-solid fa-circle-check" style="color:#22c55e;"></i>
                        Google account connected — OAuth2 active.
                    </div>
                    <?php elseif (GA4_OAUTH_CLIENT_ID && GA4_PROPERTY_ID && !vdj_ga4_oauth_ready()): ?>
                    <div style="margin-top:14px;display:flex;align-items:center;gap:8px;font-size:13px;color:#92400e;">
                        <i class="fa-solid fa-triangle-exclamation" style="color:#f59e0b;"></i>
                        Client ID saved — click <strong>Connect Google Account</strong> to authorize.
                    </div>
                    <?php endif; ?>
                </div>
            </details>
        </div>
    </div>

    <?php if ($ga4Error): ?>
    <div class="flash flash-error" style="margin-bottom:20px;">
        <i class="fa-solid fa-triangle-exclamation"></i>
        <strong>GA4 API Error:</strong> <?= e($ga4Error) ?>
    </div>
    <?php endif; ?>

    <?php if ($ga4Data): ?>
    <?php
    $s7  = $ga4Data['summary_7d'];
    $s28 = $ga4Data['summary_28d'];
    $avgDur = sprintf('%d:%02d', intdiv($s7['avg_duration'], 60), $s7['avg_duration'] % 60);
    $sparkSessions = array_map('intval', array_column($ga4Data['daily'], 'sessions'));
    $sparkMax = max($sparkSessions ?: [1]);
    $sparkW   = 6;
    $sparkGap = 3;
    $sparkH   = 40;
    ?>

    <!-- GA4 Metric Strip -->
    <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:16px;margin-bottom:20px;">
        <?php
        $strip = [
            ['Active Now',       number_format($ga4Data['active_now']), '#22c55e', 'fa-circle-dot'],
            ['Sessions (7d)',    number_format((int)$s7['sessions']),   '#7f77dd', 'fa-arrow-pointer'],
            ['Users (7d)',       number_format((int)$s7['users']),      '#3b82f6', 'fa-users'],
            ['Page Views (7d)',  number_format((int)$s7['pageviews']),  '#10b981', 'fa-eye'],
            ['Avg Session',      $avgDur,                               '#f59e0b', 'fa-clock'],
            ['Bounce Rate',      $s7['bounce_rate'].'%',               '#ef4444', 'fa-right-from-bracket'],
            ['Sessions (28d)',   number_format((int)$s28['sessions']),  '#8b5cf6', 'fa-calendar-days'],
            ['Users (28d)',      number_format((int)$s28['users']),     '#06b6d4', 'fa-person-running'],
        ];
        foreach ($strip as [$label, $val, $col, $icon]):
        ?>
        <div style="background:#fff;border:1px solid var(--border);border-radius:10px;padding:16px;">
            <div style="font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted);margin-bottom:6px;">
                <i class="fa-solid <?= $icon ?>" style="color:<?= $col ?>;margin-right:4px;"></i><?= $label ?>
            </div>
            <div style="font-size:24px;font-weight:700;font-family:'Manrope',sans-serif;color:var(--text);"><?= $val ?></div>
        </div>
        <?php endforeach; ?>
    </div>

    <!-- Sparkline + 14-day sessions -->
    <div class="admin-card" style="margin-bottom:20px;">
        <div class="admin-card__header"><h2><i class="fa-solid fa-chart-area"></i> Sessions — last 14 days</h2></div>
        <div class="admin-card__body" style="overflow-x:auto;">
            <svg width="<?= count($sparkSessions) * ($sparkW + $sparkGap) ?>" height="<?= $sparkH + 20 ?>"
                 style="display:block;min-width:100%;">
                <?php foreach ($sparkSessions as $idx => $val): ?>
                <?php $barH = $sparkMax > 0 ? max(2, intval($val / $sparkMax * $sparkH)) : 2; ?>
                <g>
                    <rect x="<?= $idx * ($sparkW + $sparkGap) ?>"
                          y="<?= $sparkH - $barH ?>"
                          width="<?= $sparkW ?>" height="<?= $barH ?>"
                          rx="2" fill="#7f77dd" opacity=".8"/>
                    <title><?= e($ga4Data['daily'][$idx]['date'] ?? '') ?>: <?= number_format($val) ?> sessions</title>
                </g>
                <?php endforeach; ?>
            </svg>
            <div style="display:flex;justify-content:space-between;font-size:11px;color:var(--text-muted);margin-top:6px;">
                <span><?= e($ga4Data['daily'][0]['date'] ?? '') ?></span>
                <span><?= e(end($ga4Data['daily'])['date'] ?? '') ?></span>
            </div>
        </div>
    </div>

    <!-- Top Pages + Countries + Devices -->
    <div style="display:grid;grid-template-columns:2fr 1fr;gap:20px;margin-bottom:20px;">

        <div class="admin-card">
            <div class="admin-card__header"><h2><i class="fa-solid fa-file-lines"></i> Top Pages (7d)</h2></div>
            <table class="admin-table">
                <thead><tr><th>Path</th><th>Views</th><th>Users</th></tr></thead>
                <tbody>
                <?php foreach ($ga4Data['top_pages'] as $pg): ?>
                <tr>
                    <td style="font-family:monospace;font-size:12px;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">
                        <span title="<?= e($pg['pageTitle'] ?? '') ?>"><?= e($pg['pagePath']) ?></span>
                    </td>
                    <td style="text-align:right;font-variant-numeric:tabular-nums;"><?= number_format((int)$pg['screenPageViews']) ?></td>
                    <td style="text-align:right;font-variant-numeric:tabular-nums;color:var(--text-muted);"><?= number_format((int)$pg['activeUsers']) ?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div style="display:flex;flex-direction:column;gap:20px;">
            <div class="admin-card">
                <div class="admin-card__header"><h2><i class="fa-solid fa-earth-europe"></i> Countries</h2></div>
                <div class="admin-card__body">
                <?php
                $totalCtry = array_sum(array_column($ga4Data['countries'], 'sessions')) ?: 1;
                foreach ($ga4Data['countries'] as $c):
                    $pct = round((int)$c['sessions'] / $totalCtry * 100);
                ?>
                <div style="margin-bottom:10px;">
                    <div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:3px;">
                        <span><?= e($c['country']) ?></span>
                        <span style="color:var(--text-muted);"><?= $pct ?>%</span>
                    </div>
                    <div style="height:5px;background:var(--border);border-radius:3px;">
                        <div style="height:5px;width:<?= $pct ?>%;background:#7f77dd;border-radius:3px;"></div>
                    </div>
                </div>
                <?php endforeach; ?>
                </div>
            </div>

            <div class="admin-card">
                <div class="admin-card__header"><h2><i class="fa-solid fa-mobile-screen"></i> Devices</h2></div>
                <div class="admin-card__body">
                <?php
                $totalDev = array_sum(array_column($ga4Data['devices'], 'sessions')) ?: 1;
                $devIcons = ['desktop'=>'fa-desktop','mobile'=>'fa-mobile-screen','tablet'=>'fa-tablet-screen-button'];
                foreach ($ga4Data['devices'] as $d):
                    $cat  = strtolower($d['deviceCategory']);
                    $icon = $devIcons[$cat] ?? 'fa-display';
                    $pct  = round((int)$d['sessions'] / $totalDev * 100);
                ?>
                <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px;">
                    <i class="fa-solid <?= $icon ?>" style="color:#7f77dd;width:16px;text-align:center;"></i>
                    <span style="flex:1;font-size:13px;text-transform:capitalize;"><?= e($cat) ?></span>
                    <span style="font-size:13px;font-weight:600;"><?= $pct ?>%</span>
                </div>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <div style="font-size:11px;color:var(--text-muted);margin-bottom:20px;">
        Data cached for 5 min · Last fetched: <?= date('Y-m-d H:i:s', $ga4Data['fetched_at']) ?> · Property: <?= e(GA4_PROPERTY_ID) ?>
    </div>
    <?php endif; // $ga4Data ?>

    <hr style="border:none;border-top:2px solid var(--border);margin:8px 0 28px;">
    <h2 style="font-size:18px;font-weight:700;margin-bottom:20px;"><i class="fa-solid fa-database" style="color:#7f77dd;"></i> Database Growth (last 30 days)</h2>

    <!-- ── Summary Mini-Cards ─────────────────────────────────────────────── -->
    <div class="analytics-summary">
        <div class="stat-card">
            <div class="stat-card__icon"><i class="fa-solid fa-users"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($totalUsers) ?></div>
                <div class="stat-card__label">Total Users</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon"><i class="fa-solid fa-border-all"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($totalBoards) ?></div>
                <div class="stat-card__label">Total Boards</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(244,63,94,.1);color:#f43f5e;">
                <i class="fa-solid fa-heart"></i>
            </div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($totalLikes) ?></div>
                <div class="stat-card__label">Total Likes</div>
            </div>
        </div>
    </div>

    <!-- ── Line Charts: Users & Boards Per Day ───────────────────────────── -->
    <div class="analytics-two-col">

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-user-plus"></i> New Users — Last 30 Days</h2>
            </div>
            <div class="chart-wrap">
                <canvas id="chartUsersDay"></canvas>
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-border-all"></i> New Boards — Last 30 Days</h2>
            </div>
            <div class="chart-wrap">
                <canvas id="chartBoardsDay"></canvas>
            </div>
        </div>

    </div>

    <!-- ── Bar Chart: Top Boards + Doughnut: Tags ────────────────────────── -->
    <div class="analytics-two-col">

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-fire"></i> Top 10 Most Liked Boards</h2>
            </div>
            <div class="chart-wrap" style="max-height:340px;overflow:hidden;">
                <canvas id="chartTopBoards"></canvas>
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-tags"></i> Top Style Tags</h2>
            </div>
            <div class="chart-wrap" style="display:flex;align-items:center;justify-content:center;">
                <canvas id="chartTags" style="max-height:300px;max-width:300px;"></canvas>
            </div>
        </div>

    </div>

    <!-- ── Doughnut: Board Status + User Breakdown ───────────────────────── -->
    <div class="analytics-two-col">

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-chart-pie"></i> Board Status</h2>
            </div>
            <div class="chart-wrap" style="display:flex;align-items:center;justify-content:center;">
                <canvas id="chartBoardStatus" style="max-height:280px;max-width:280px;"></canvas>
            </div>
            <div style="padding:0 20px 16px;display:flex;gap:20px;justify-content:center;font-size:13px;">
                <span style="display:flex;align-items:center;gap:6px;">
                    <span class="breakdown-dot" style="background:#22c55e;"></span>
                    Published: <strong><?= number_format($publishedCount) ?></strong>
                </span>
                <span style="display:flex;align-items:center;gap:6px;">
                    <span class="breakdown-dot" style="background:#f59e0b;"></span>
                    Draft: <strong><?= number_format($draftCount) ?></strong>
                </span>
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-users"></i> User Breakdown</h2>
            </div>
            <div class="user-breakdown-stat">
                <span class="label">
                    <span class="breakdown-dot" style="background:var(--accent);"></span>
                    Total Users
                </span>
                <span class="value"><?= number_format($totalUsers) ?></span>
            </div>
            <div class="user-breakdown-stat">
                <span class="label">
                    <span class="breakdown-dot" style="background:#f43f5e;"></span>
                    Admin Users
                </span>
                <span class="value" style="color:var(--accent);"><?= number_format($adminCount) ?></span>
            </div>
            <div class="user-breakdown-stat">
                <span class="label">
                    <span class="breakdown-dot" style="background:#22c55e;"></span>
                    Regular Users
                </span>
                <span class="value"><?= number_format($regularCount) ?></span>
            </div>
            <?php if ($totalUsers > 0): ?>
            <div style="padding:16px 20px;">
                <div style="font-size:12px;color:var(--text-muted);margin-bottom:8px;">Admin ratio</div>
                <div style="background:#f1f5f9;border-radius:99px;height:8px;overflow:hidden;">
                    <div style="background:var(--accent);height:100%;width:<?= round($adminCount / $totalUsers * 100, 1) ?>%;border-radius:99px;transition:width .4s;"></div>
                </div>
                <div style="font-size:12px;color:var(--text-muted);margin-top:5px;">
                    <?= round($adminCount / $totalUsers * 100, 1) ?>% of all users are admins
                </div>
            </div>
            <?php endif; ?>
        </div>

    </div>

    <!-- ── Revenue Analytics ────────────────────────────────────────────── -->
    <h2 style="font-size:15px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;margin:0 0 14px;">
        <i class="fa-solid fa-chart-line" style="margin-right:6px;"></i> Revenue &amp; Monetization
    </h2>
    <div class="analytics-two-col">

        <!-- Sponsor Lead Funnel -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-handshake"></i> Sponsor Lead Funnel</h2>
            </div>
            <?php if ($sponsorStats['total'] === 0): ?>
                <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
                    <i class="fa-solid fa-circle-info" style="font-size:28px;margin-bottom:10px;display:block;opacity:.4;"></i>
                    No data yet — run <code>schema-update.sql</code> to create the <code>sponsor_leads</code> table.
                </div>
            <?php else: ?>
                <div class="revenue-funnel-grid">
                    <div class="funnel-stat">
                        <span class="funnel-stat__icon" style="color:#3b82f6;"><i class="fa-solid fa-star"></i></span>
                        <span class="funnel-stat__num" style="color:#3b82f6;"><?= number_format($sponsorStats['new']) ?></span>
                        <span class="funnel-stat__label">New</span>
                    </div>
                    <div class="funnel-stat">
                        <span class="funnel-stat__icon" style="color:#f59e0b;"><i class="fa-solid fa-phone"></i></span>
                        <span class="funnel-stat__num" style="color:#f59e0b;"><?= number_format($sponsorStats['contacted']) ?></span>
                        <span class="funnel-stat__label">Contacted</span>
                    </div>
                    <div class="funnel-stat">
                        <span class="funnel-stat__icon" style="color:#22c55e;"><i class="fa-solid fa-trophy"></i></span>
                        <span class="funnel-stat__num" style="color:#22c55e;"><?= number_format($sponsorStats['won']) ?></span>
                        <span class="funnel-stat__label">Won</span>
                    </div>
                    <div class="funnel-stat">
                        <span class="funnel-stat__icon" style="color:#f43f5e;"><i class="fa-solid fa-xmark"></i></span>
                        <span class="funnel-stat__num" style="color:#f43f5e;"><?= number_format($sponsorStats['lost']) ?></span>
                        <span class="funnel-stat__label">Lost</span>
                    </div>
                </div>
                <div class="revenue-win-rate">
                    <span class="win-rate-badge"><?= $sponsorStats['win_rate'] ?>%</span>
                    <span class="win-rate-label">Win rate<br><span style="color:var(--text);font-size:12px;"><?= number_format($sponsorStats['won']) ?> won out of <?= number_format($sponsorStats['won'] + $sponsorStats['lost']) ?> closed leads</span></span>
                </div>
            <?php endif; ?>
            <div class="revenue-card-footer">
                <a href="/admin/sponsors.php" style="color:var(--accent);text-decoration:none;font-weight:500;">
                    <i class="fa-solid fa-arrow-right" style="margin-right:4px;font-size:11px;"></i> Manage sponsor leads
                </a>
            </div>
        </div>

        <!-- Newsletter Subscribers -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-envelope"></i> Newsletter Subscribers</h2>
            </div>
            <?php if ($newsletterStats['total'] === 0): ?>
                <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
                    <i class="fa-solid fa-circle-info" style="font-size:28px;margin-bottom:10px;display:block;opacity:.4;"></i>
                    No subscriber data yet — ensure the <code>newsletter_subscribers</code> table exists.
                </div>
            <?php else: ?>
                <div class="newsletter-stats-grid">
                    <div class="newsletter-stat">
                        <span style="font-size:18px;color:var(--accent);"><i class="fa-solid fa-envelope"></i></span>
                        <span class="newsletter-stat__num" style="color:var(--accent);"><?= number_format($newsletterStats['total']) ?></span>
                        <span class="newsletter-stat__label">Total</span>
                    </div>
                    <div class="newsletter-stat">
                        <span style="font-size:18px;color:#22c55e;"><i class="fa-solid fa-circle-check"></i></span>
                        <span class="newsletter-stat__num" style="color:#22c55e;"><?= number_format($newsletterStats['active']) ?></span>
                        <span class="newsletter-stat__label">Active</span>
                    </div>
                    <div class="newsletter-stat">
                        <span style="font-size:18px;color:#94a3b8;"><i class="fa-solid fa-circle-xmark"></i></span>
                        <span class="newsletter-stat__num" style="color:#94a3b8;"><?= number_format($newsletterStats['total'] - $newsletterStats['active']) ?></span>
                        <span class="newsletter-stat__label">Unsubscribed</span>
                    </div>
                </div>
                <?php if ($newsletterStats['total'] > 0): ?>
                <div style="padding:0 20px 16px;">
                    <div style="font-size:12px;color:var(--text-muted);margin-bottom:6px;">Active rate</div>
                    <div style="background:#f1f5f9;border-radius:99px;height:8px;overflow:hidden;">
                        <div style="background:#22c55e;height:100%;width:<?= round($newsletterStats['active'] / $newsletterStats['total'] * 100, 1) ?>%;border-radius:99px;transition:width .4s;"></div>
                    </div>
                    <div style="font-size:12px;color:var(--text-muted);margin-top:5px;">
                        <?= round($newsletterStats['active'] / $newsletterStats['total'] * 100, 1) ?>% of subscribers are active
                    </div>
                </div>
                <?php endif; ?>
            <?php endif; ?>
            <div class="revenue-card-footer">
                <a href="/admin/export-subscribers.php" style="color:var(--accent);text-decoration:none;font-weight:500;">
                    <i class="fa-solid fa-file-export" style="margin-right:4px;font-size:11px;"></i> Export subscribers
                </a>
            </div>
        </div>

    </div>

    <!-- ── Traffic & Visitors ───────────────────────────────────────────── -->
    <h2 style="font-size:15px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;margin:0 0 14px;">
        <i class="fa-solid fa-chart-mixed" style="margin-right:6px;"></i> Traffic &amp; Visitors
    </h2>

    <?php if (!$hasTraffic): ?>
    <div class="admin-card" style="margin-bottom:28px;">
        <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
            <i class="fa-solid fa-signal" style="font-size:30px;margin-bottom:10px;display:block;opacity:.35;"></i>
            No traffic data yet — <code>api/track.php</code> + <code>schema-update.sql</code> must be deployed first.<br>
            <span style="font-size:12px;margin-top:6px;display:block;">Views will appear here automatically once visitors start hitting the site.</span>
        </div>
    </div>
    <?php else: ?>

    <!-- Traffic summary cards -->
    <div class="analytics-summary" style="grid-template-columns:repeat(4,1fr);margin-bottom:20px;">
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(59,130,246,.1);color:#3b82f6;"><i class="fa-solid fa-eye"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($trafficStats['total']) ?></div>
                <div class="stat-card__label">Page Views (30d)</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(245,158,11,.1);color:#f59e0b;"><i class="fa-solid fa-user-secret"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($trafficStats['guests']) ?></div>
                <div class="stat-card__label">Guest Views</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(34,197,94,.1);color:#22c55e;"><i class="fa-solid fa-user-check"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($trafficStats['registered']) ?></div>
                <div class="stat-card__label">Member Views</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(139,92,246,.1);color:#8b5cf6;"><i class="fa-solid fa-fingerprint"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($trafficStats['unique']) ?></div>
                <div class="stat-card__label">Unique Visitors</div>
            </div>
        </div>
    </div>

    <!-- Views per day + Device breakdown -->
    <div class="analytics-two-col">
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-chart-area"></i> Views Per Day — Last 30 Days</h2>
            </div>
            <div class="chart-wrap">
                <canvas id="chartViewsDay"></canvas>
            </div>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-mobile-screen-button"></i> Device Breakdown</h2>
            </div>
            <div class="chart-wrap" style="display:flex;align-items:center;justify-content:center;">
                <canvas id="chartDevices" style="max-height:260px;max-width:260px;"></canvas>
            </div>
            <div style="padding:0 20px 16px;display:flex;gap:18px;justify-content:center;flex-wrap:wrap;font-size:13px;">
                <span style="display:flex;align-items:center;gap:6px;">
                    <span class="breakdown-dot" style="background:#3b82f6;"></span>
                    Desktop: <strong><?= number_format($deviceBreak['desktop']) ?></strong>
                </span>
                <span style="display:flex;align-items:center;gap:6px;">
                    <span class="breakdown-dot" style="background:#f59e0b;"></span>
                    Mobile: <strong><?= number_format($deviceBreak['mobile']) ?></strong>
                </span>
                <span style="display:flex;align-items:center;gap:6px;">
                    <span class="breakdown-dot" style="background:#22c55e;"></span>
                    Tablet: <strong><?= number_format($deviceBreak['tablet']) ?></strong>
                </span>
            </div>
        </div>
    </div>

    <!-- Top pages + Top referrers -->
    <div class="analytics-two-col">
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-file-lines"></i> Top 10 Pages (30d)</h2>
            </div>
            <table style="width:100%;border-collapse:collapse;font-size:13px;">
                <thead>
                    <tr style="border-bottom:2px solid #f1f5f9;">
                        <th style="text-align:left;padding:8px 20px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Page</th>
                        <th style="text-align:right;padding:8px 20px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Views</th>
                        <th style="text-align:right;padding:8px 20px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Unique</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($topPages as $pg):
                    $pgLabel = mb_strimwidth($pg['page_path'], 0, 48, '…');
                    $pgTitle = $pg['page_title'] ? mb_strimwidth($pg['page_title'], 0, 36, '…') : '';
                ?>
                    <tr style="border-bottom:1px solid #f8fafc;">
                        <td style="padding:9px 20px;">
                            <div style="font-weight:500;color:var(--text);"><?= htmlspecialchars($pgLabel, ENT_QUOTES) ?></div>
                            <?php if ($pgTitle): ?><div style="font-size:11px;color:var(--text-muted);"><?= htmlspecialchars($pgTitle, ENT_QUOTES) ?></div><?php endif; ?>
                        </td>
                        <td style="padding:9px 20px;text-align:right;font-weight:700;font-family:'Manrope',sans-serif;"><?= number_format((int)$pg['views']) ?></td>
                        <td style="padding:9px 20px;text-align:right;color:var(--text-muted);"><?= number_format((int)$pg['uniques']) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-arrow-turn-down-right"></i> Top Referrers (30d)</h2>
            </div>
            <?php if (empty($topReferrers)): ?>
                <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:13px;">
                    <i class="fa-solid fa-link" style="font-size:26px;display:block;margin-bottom:8px;opacity:.35;"></i>
                    No external referrers recorded yet.
                </div>
            <?php else: ?>
                <?php
                $maxRef = max(array_column($topReferrers, 'cnt'));
                foreach ($topReferrers as $rf):
                    $pct = $maxRef > 0 ? round($rf['cnt'] / $maxRef * 100) : 0;
                ?>
                <div style="padding:10px 20px;border-bottom:1px solid #f8fafc;">
                    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
                        <span style="font-size:13px;font-weight:500;color:var(--text);max-width:70%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">
                            <?= htmlspecialchars($rf['referrer'], ENT_QUOTES) ?>
                        </span>
                        <span style="font-size:13px;font-weight:700;font-family:'Manrope',sans-serif;"><?= number_format((int)$rf['cnt']) ?></span>
                    </div>
                    <div style="background:#f1f5f9;border-radius:99px;height:5px;overflow:hidden;">
                        <div style="background:var(--accent);height:100%;width:<?= $pct ?>%;border-radius:99px;"></div>
                    </div>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; // hasTraffic ?>

    <!-- ── Board Clicks ───────────────────────────────────────────────────── -->
    <h2 style="font-size:15px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;margin:0 0 14px;">
        <i class="fa-solid fa-computer-mouse" style="margin-right:6px;"></i> Board Clicks
    </h2>

    <?php if (!$hasClicks): ?>
    <div class="admin-card" style="margin-bottom:28px;">
        <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
            <i class="fa-solid fa-computer-mouse" style="font-size:30px;margin-bottom:10px;display:block;opacity:.35;"></i>
            No click data yet. Board clicks are tracked automatically once the updated <code>main.js</code> is live.
        </div>
    </div>
    <?php else: ?>
    <!-- Click summary -->
    <div class="analytics-summary" style="grid-template-columns:repeat(3,1fr);margin-bottom:20px;">
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(127,119,221,.1);color:var(--accent);"><i class="fa-solid fa-computer-mouse"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($clickStats['total']) ?></div>
                <div class="stat-card__label">Total Clicks (30d)</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(245,158,11,.1);color:#f59e0b;"><i class="fa-solid fa-user-secret"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($clickStats['guests']) ?></div>
                <div class="stat-card__label">Guest Clicks</div>
            </div>
        </div>
        <div class="stat-card">
            <div class="stat-card__icon" style="background:rgba(34,197,94,.1);color:#22c55e;"><i class="fa-solid fa-user-check"></i></div>
            <div class="stat-card__body">
                <div class="stat-card__num"><?= number_format($clickStats['registered']) ?></div>
                <div class="stat-card__label">Member Clicks</div>
            </div>
        </div>
    </div>

    <div class="analytics-two-col">
        <!-- Top clicked boards -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-fire"></i> Top Clicked Boards (30d)</h2>
            </div>
            <table style="width:100%;border-collapse:collapse;font-size:13px;">
                <thead>
                    <tr style="border-bottom:2px solid #f1f5f9;">
                        <th style="text-align:left;padding:8px 20px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Board</th>
                        <th style="text-align:right;padding:8px 12px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Clicks</th>
                        <th style="text-align:right;padding:8px 12px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Views</th>
                        <th style="text-align:right;padding:8px 20px;color:var(--text-muted);font-weight:600;font-size:11px;text-transform:uppercase;">Likes</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($topClickedBoards as $cb):
                    $cLabel = mb_strimwidth($cb['title'], 0, 32, '…');
                ?>
                    <tr style="border-bottom:1px solid #f8fafc;">
                        <td style="padding:9px 20px;">
                            <a href="/board.php?id=<?= (int)$cb['board_id'] ?>" target="_blank" style="font-weight:500;color:var(--text);text-decoration:none;" onmouseover="this.style.color='var(--accent)'" onmouseout="this.style.color='var(--text)'">
                                <?= htmlspecialchars($cLabel, ENT_QUOTES) ?>
                            </a>
                        </td>
                        <td style="padding:9px 12px;text-align:right;font-weight:700;color:var(--accent);font-family:'Manrope',sans-serif;"><?= number_format((int)$cb['clicks']) ?></td>
                        <td style="padding:9px 12px;text-align:right;color:var(--text-muted);"><?= number_format((int)$cb['view_count']) ?></td>
                        <td style="padding:9px 20px;text-align:right;color:#f43f5e;"><?= number_format((int)$cb['likes']) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <!-- Clicks by source doughnut -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-circle-nodes"></i> Click Source Breakdown</h2>
            </div>
            <div class="chart-wrap" style="display:flex;align-items:center;justify-content:center;">
                <canvas id="chartClickSrc" style="max-height:260px;max-width:260px;"></canvas>
            </div>
        </div>
    </div>
    <?php endif; // hasClicks ?>

    <!-- ── Follow Analytics ─────────────────────────────────────────────── -->
    <h2 style="font-size:15px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;margin:0 0 14px;">
        <i class="fa-solid fa-user-group" style="margin-right:6px;"></i> Follow Analytics
    </h2>
    <?php if (empty($topFollowed) && empty(array_filter($followDayCounts))): ?>
        <div class="admin-card">
            <div style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
                <i class="fa-solid fa-circle-info" style="font-size:28px;margin-bottom:10px;display:block;opacity:.4;"></i>
                No follow data — <code>follows</code> table not found or empty.
            </div>
        </div>
    <?php else: ?>
    <div class="analytics-two-col">

        <!-- Follow Activity Line Chart -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-user-plus"></i> Follow Activity — Last 30 Days</h2>
            </div>
            <div class="chart-wrap">
                <canvas id="chartFollowsDay"></canvas>
            </div>
        </div>

        <!-- Top 10 Most-Followed -->
        <div class="admin-card">
            <div class="admin-card__header">
                <h2><i class="fa-solid fa-ranking-star"></i> Top 10 Most-Followed Curators</h2>
            </div>
            <?php if (empty($topFollowed)): ?>
                <div class="empty-state" style="padding:30px 20px;text-align:center;color:var(--text-muted);font-size:14px;">
                    No users found.
                </div>
            <?php else: ?>
            <ul class="top-followed-list">
                <?php foreach ($topFollowed as $i => $u): ?>
                <li class="top-followed-item">
                    <span class="top-followed-rank">#<?= $i + 1 ?></span>
                    <a class="top-followed-username" href="/profile.php?u=<?= urlencode($u['username']) ?>">
                        <?= htmlspecialchars($u['username'], ENT_QUOTES) ?>
                        <?php if ((int)$u['is_verified'] === 1): ?>
                            <i class="fa-solid fa-circle-check verified-badge" title="Verified"></i>
                        <?php endif; ?>
                    </a>
                    <span class="top-followed-count"><?= number_format((int)$u['follower_count']) ?></span>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>

    </div>
    <?php endif; ?>

</main>

<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
// ── Data from PHP ───────────────────────────────────────────────────────────
const userDayLabels  = <?= json_encode($userDayLabels) ?>;
const userDayCounts  = <?= json_encode($userDayCounts) ?>;
const boardDayLabels = <?= json_encode($boardDayLabels) ?>;
const boardDayCounts = <?= json_encode($boardDayCounts) ?>;
const topBoardLabels = <?= json_encode($topBoardLabels) ?>;
const topBoardCounts = <?= json_encode(array_map('intval', $topBoardCounts)) ?>;
const tagLabels      = <?= json_encode($tagLabels) ?>;
const tagValues      = <?= json_encode(array_map('intval', $tagValues)) ?>;
const publishedCount   = <?= (int)$publishedCount ?>;
const draftCount       = <?= (int)$draftCount ?>;
const followDayLabels  = <?= json_encode($followDayLabels) ?>;
const followDayCounts  = <?= json_encode(array_map('intval', $followDayCounts)) ?>;

// ── Shared chart defaults ───────────────────────────────────────────────────
Chart.defaults.font.family = "'Inter', sans-serif";
Chart.defaults.font.size   = 12;
Chart.defaults.color       = '#64748b';

const accent     = '#7F77DD';
const accentFill = 'rgba(127,119,221,0.15)';

// ── Helpers ──────────────────────────────────────────────────────────────────
function formatDayLabel(dateStr) {
    const d = new Date(dateStr + 'T00:00:00');
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

// ── Chart: New Users per day ─────────────────────────────────────────────────
new Chart(document.getElementById('chartUsersDay'), {
    type: 'line',
    data: {
        labels: userDayLabels.map(formatDayLabel),
        datasets: [{
            label: 'New Users',
            data: userDayCounts,
            borderColor: accent,
            backgroundColor: accentFill,
            borderWidth: 2,
            pointRadius: 3,
            pointBackgroundColor: accent,
            fill: true,
            tension: 0.35,
        }]
    },
    options: {
        responsive: true,
        plugins: {
            legend: { display: false },
            tooltip: {
                callbacks: {
                    title: function(items) { return userDayLabels[items[0].dataIndex]; }
                }
            }
        },
        scales: {
            x: {
                grid: { display: false },
                ticks: {
                    maxTicksLimit: 8,
                    maxRotation: 0,
                }
            },
            y: {
                beginAtZero: true,
                grid: { color: '#f1f5f9' },
                ticks: { precision: 0 }
            }
        }
    }
});

// ── Chart: New Boards per day ─────────────────────────────────────────────────
new Chart(document.getElementById('chartBoardsDay'), {
    type: 'line',
    data: {
        labels: boardDayLabels.map(formatDayLabel),
        datasets: [{
            label: 'New Boards',
            data: boardDayCounts,
            borderColor: '#f43f5e',
            backgroundColor: 'rgba(244,63,94,0.12)',
            borderWidth: 2,
            pointRadius: 3,
            pointBackgroundColor: '#f43f5e',
            fill: true,
            tension: 0.35,
        }]
    },
    options: {
        responsive: true,
        plugins: {
            legend: { display: false },
            tooltip: {
                callbacks: {
                    title: function(items) { return boardDayLabels[items[0].dataIndex]; }
                }
            }
        },
        scales: {
            x: {
                grid: { display: false },
                ticks: { maxTicksLimit: 8, maxRotation: 0 }
            },
            y: {
                beginAtZero: true,
                grid: { color: '#f1f5f9' },
                ticks: { precision: 0 }
            }
        }
    }
});

// ── Chart: Top 10 Boards (horizontal bar) ────────────────────────────────────
new Chart(document.getElementById('chartTopBoards'), {
    type: 'bar',
    data: {
        labels: topBoardLabels,
        datasets: [{
            label: 'Likes',
            data: topBoardCounts,
            backgroundColor: 'rgba(127,119,221,0.75)',
            borderColor: accent,
            borderWidth: 1,
            borderRadius: 4,
        }]
    },
    options: {
        indexAxis: 'y',
        responsive: true,
        plugins: {
            legend: { display: false },
        },
        scales: {
            x: {
                beginAtZero: true,
                grid: { color: '#f1f5f9' },
                ticks: { precision: 0 }
            },
            y: {
                grid: { display: false },
                ticks: { font: { size: 11 } }
            }
        }
    }
});

// ── Chart: Top Style Tags (doughnut) ─────────────────────────────────────────
const tagPalette = [
    'rgba(127,119,221,0.85)',
    'rgba(244,63,94,0.75)',
    'rgba(34,197,94,0.75)',
    'rgba(245,158,11,0.75)',
    'rgba(59,130,246,0.75)',
    'rgba(168,85,247,0.75)',
    'rgba(20,184,166,0.75)',
    'rgba(251,146,60,0.75)',
];
new Chart(document.getElementById('chartTags'), {
    type: 'doughnut',
    data: {
        labels: tagLabels.length ? tagLabels : ['No tags yet'],
        datasets: [{
            data: tagValues.length ? tagValues : [1],
            backgroundColor: tagPalette,
            borderWidth: 2,
            borderColor: '#fff',
        }]
    },
    options: {
        responsive: true,
        plugins: {
            legend: {
                position: 'bottom',
                labels: { boxWidth: 12, padding: 12, font: { size: 12 } }
            }
        },
        cutout: '60%',
    }
});

// ── Chart: Views per day (guest vs registered stacked) ───────────────────────
<?php if ($hasTraffic): ?>
const viewDayLabels    = <?= json_encode(array_column($viewsByDay, 'd')) ?>;
const viewGuestCounts  = <?= json_encode(array_column($viewsByDay, 'guests')) ?>;
const viewRegCounts    = <?= json_encode(array_column($viewsByDay, 'registered')) ?>;

if (document.getElementById('chartViewsDay')) {
    new Chart(document.getElementById('chartViewsDay'), {
        type: 'line',
        data: {
            labels: viewDayLabels.map(formatDayLabel),
            datasets: [
                {
                    label: 'Guest Views',
                    data: viewGuestCounts,
                    borderColor: '#f59e0b',
                    backgroundColor: 'rgba(245,158,11,0.10)',
                    borderWidth: 2,
                    pointRadius: 2,
                    pointBackgroundColor: '#f59e0b',
                    fill: true,
                    tension: 0.35,
                    order: 2,
                },
                {
                    label: 'Member Views',
                    data: viewRegCounts,
                    borderColor: '#22c55e',
                    backgroundColor: 'rgba(34,197,94,0.10)',
                    borderWidth: 2,
                    pointRadius: 2,
                    pointBackgroundColor: '#22c55e',
                    fill: true,
                    tension: 0.35,
                    order: 1,
                }
            ]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { position: 'top', labels: { boxWidth: 12, padding: 14 } },
                tooltip: { callbacks: { title: function(items) { return viewDayLabels[items[0].dataIndex]; } } }
            },
            scales: {
                x: { grid: { display: false }, ticks: { maxTicksLimit: 8, maxRotation: 0 } },
                y: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { precision: 0 }, stacked: false }
            }
        }
    });
}

// ── Chart: Device breakdown (doughnut) ───────────────────────────────────────
if (document.getElementById('chartDevices')) {
    new Chart(document.getElementById('chartDevices'), {
        type: 'doughnut',
        data: {
            labels: ['Desktop', 'Mobile', 'Tablet'],
            datasets: [{
                data: [<?= (int)$deviceBreak['desktop'] ?>, <?= (int)$deviceBreak['mobile'] ?>, <?= (int)$deviceBreak['tablet'] ?>],
                backgroundColor: ['rgba(59,130,246,0.8)', 'rgba(245,158,11,0.8)', 'rgba(34,197,94,0.8)'],
                borderWidth: 2,
                borderColor: '#fff',
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { position: 'bottom', labels: { boxWidth: 12, padding: 12 } }
            },
            cutout: '60%',
        }
    });
}
<?php endif; ?>

<?php if ($hasClicks): ?>
// ── Chart: Click source breakdown (doughnut) ─────────────────────────────────
const clickSrcLabels = <?= json_encode(array_keys($clicksBySource)) ?>;
const clickSrcValues = <?= json_encode(array_values($clicksBySource)) ?>;
if (document.getElementById('chartClickSrc')) {
    new Chart(document.getElementById('chartClickSrc'), {
        type: 'doughnut',
        data: {
            labels: clickSrcLabels.length ? clickSrcLabels.map(s => s.charAt(0).toUpperCase()+s.slice(1)) : ['No data'],
            datasets: [{
                data: clickSrcValues.length ? clickSrcValues : [1],
                backgroundColor: [
                    'rgba(127,119,221,0.8)',
                    'rgba(244,63,94,0.75)',
                    'rgba(34,197,94,0.75)',
                    'rgba(245,158,11,0.75)',
                    'rgba(59,130,246,0.75)',
                    'rgba(168,85,247,0.75)',
                ],
                borderWidth: 2,
                borderColor: '#fff',
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { position: 'bottom', labels: { boxWidth: 12, padding: 12 } }
            },
            cutout: '60%',
        }
    });
}
<?php endif; ?>

// ── Chart: Follow Activity per day ───────────────────────────────────────────
if (document.getElementById('chartFollowsDay')) {
    new Chart(document.getElementById('chartFollowsDay'), {
        type: 'line',
        data: {
            labels: followDayLabels.map(formatDayLabel),
            datasets: [{
                label: 'New Follows',
                data: followDayCounts,
                borderColor: '#8b5cf6',
                backgroundColor: 'rgba(139,92,246,0.12)',
                borderWidth: 2,
                pointRadius: 3,
                pointBackgroundColor: '#8b5cf6',
                fill: true,
                tension: 0.35,
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { display: false },
                tooltip: {
                    callbacks: {
                        title: function(items) { return followDayLabels[items[0].dataIndex]; }
                    }
                }
            },
            scales: {
                x: {
                    grid: { display: false },
                    ticks: { maxTicksLimit: 8, maxRotation: 0 }
                },
                y: {
                    beginAtZero: true,
                    grid: { color: '#f1f5f9' },
                    ticks: { precision: 0 }
                }
            }
        }
    });
}

// ── Chart: Board Status (doughnut) ───────────────────────────────────────────
new Chart(document.getElementById('chartBoardStatus'), {
    type: 'doughnut',
    data: {
        labels: ['Published', 'Draft'],
        datasets: [{
            data: [publishedCount, draftCount],
            backgroundColor: ['rgba(34,197,94,0.8)', 'rgba(245,158,11,0.8)'],
            borderWidth: 2,
            borderColor: '#fff',
        }]
    },
    options: {
        responsive: true,
        plugins: {
            legend: {
                display: false,
            }
        },
        cutout: '60%',
    }
});
</script>
</body>
</html>
