<?php
/**
 * admin/ga4-callback.php — Google OAuth2 callback for GA4
 * Exchanges the authorization code for tokens and stores the refresh token.
 */
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/../includes/ga4.php';

$error = '';

if (isset($_GET['error'])) {
    $error = 'Google authorization denied: ' . e($_GET['error']);
} elseif (empty($_GET['code'])) {
    $error = 'No authorization code received.';
} else {
    $cfg = vdj_ga4_oauth_config();
    if (!$cfg['client_id'] || !$cfg['client_secret']) {
        $error = 'OAuth2 Client ID / Secret not configured. Set them in the Analytics page first.';
    } else {
        // Exchange code for tokens
        $postData = http_build_query([
            'code'          => $_GET['code'],
            'client_id'     => $cfg['client_id'],
            'client_secret' => $cfg['client_secret'],
            'redirect_uri'  => $cfg['redirect_uri'],
            'grant_type'    => 'authorization_code',
        ]);

        [$raw, $code] = vdj_ga4_http(
            'https://oauth2.googleapis.com/token',
            $postData,
            'application/x-www-form-urlencoded'
        );
        $resp = json_decode($raw, true);

        if (!empty($resp['refresh_token'])) {
            // Save refresh token
            $php  = "<?php\n// Generated by /admin/ga4-callback.php — do not edit manually\n";
            $php .= "define('GA4_OAUTH_REFRESH_TOKEN', " . var_export($resp['refresh_token'], true) . ");\n";
            file_put_contents(GA4_OAUTH_FILE, $php, LOCK_EX);
            // Clear cache so fresh data loads
            foreach (glob(GA4_CACHE_DIR . '/ga4-*.json') ?: [] as $f) unlink($f);
            header('Location: /admin/analytics.php?ga4=connected');
            exit;
        } elseif (!empty($resp['access_token']) && empty($resp['refresh_token'])) {
            $error = 'Google returned an access token but no refresh token. Make sure you selected "offline" access and revoke previous access at <a href="https://myaccount.google.com/permissions" target="_blank">myaccount.google.com/permissions</a>, then try connecting again.';
        } else {
            $msg = $resp['error_description'] ?? $resp['error'] ?? substr($raw, 0, 200);
            $error = 'Token exchange failed: ' . $msg;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>GA4 OAuth — Admin</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <link rel="stylesheet" href="/admin/admin.css">
</head>
<body style="display:flex;align-items:center;justify-content:center;min-height:100vh;background:#f8fafc;">
  <div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:40px;max-width:480px;text-align:center;">
    <i class="fa-solid fa-triangle-exclamation" style="font-size:40px;color:#ef4444;margin-bottom:16px;display:block;"></i>
    <h2 style="margin:0 0 12px;font-size:20px;">GA4 Connection Failed</h2>
    <p style="color:#64748b;font-size:14px;line-height:1.6;"><?= $error ?></p>
    <a href="/admin/analytics.php" style="display:inline-flex;align-items:center;gap:8px;margin-top:20px;background:#7f77dd;color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600;">
      <i class="fa-solid fa-arrow-left"></i> Back to Analytics
    </a>
  </div>
</body>
</html>
